<a href="https://colab.research.google.com/github/arcctg/kpi-ml-lab1/blob/main/task_1_ukrstat_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Додайємо всі потрібні (і можливо потрібні) для обробки даних імпорти

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics
import re

Завантажуєм датасет, скачаний з ukrstat та закинутий в гітхаб репо для зручності. Датасет показує динаміку цін

In [3]:
url = 'https://raw.githubusercontent.com/arcctg/kpi-ml-lab1/main/ukrstat_prices.csv'

try:
    df = pd.read_csv(url)
    print("Data was loaded successfully:")
    display(df.head())
except Exception as e:
    print(f"Error on load: {e}")

Data was loaded successfully:

,Показник,Базисний період,Територіальний розріз,Тип товарів і послуг,Періодичність,Одиниця виміру,Масштабування,Кількість десяткових знаків,Спеціальне значення даних,Примітки часового ряду,...,2025-M04,2025-M05,2025-M06,2025-M07,2025-M08,2025-M09,2025-M10,2025-M11,2025-M12,2026-M01
0,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Птиця (тушки курячі),Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,98.15,107.22,113.94,115.55,117.95,118.03,119.98,117.93,116.20,112.47
1,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Сигарети без фільтру,Місячна,Пачка (20 шт),Одиниці,Два,Явищ не було,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,"Молоко пастеризоване жирністю до 2,6% включно",Місячна,1000 г,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,47.71,47.39,47.18,47.10,47.72,47.45,49.20,49.05,49.56,49.95
3,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Судинорозширювальні засоби імпортні,Місячна,"10 табл., капсул",Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,82.99,83.16,83.94,85.89,88.92,95.83,96.36,92.66,89.29,88.39
4,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Сигарети з фільтром медіум класу,Місячна,Пачка (20 шт),Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,111.33,113.69,116.52,119.36,121.91,123.37,126.06,128.15,130.70,133.03

Розмір датасета велий як видно, тому треба його зменшити

In [20]:
df.shape

(2449, 467)

Для почтку відільтруємо за територією та показником, як видно нижче територія включає як всю Україну так і області. Показниках половину займають індекси

In [11]:
df.head(10)

,Показник,Базисний період,Територіальний розріз,Тип товарів і послуг,Періодичність,Одиниця виміру,Масштабування,Кількість десяткових знаків,Спеціальне значення даних,Примітки часового ряду,...,2025-M04,2025-M05,2025-M06,2025-M07,2025-M08,2025-M09,2025-M10,2025-M11,2025-M12,2026-M01
0,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Птиця (тушки курячі),Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,98.15,107.22,113.94,115.55,117.95,118.03,119.98,117.93,116.20,112.47
1,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Сигарети без фільтру,Місячна,Пачка (20 шт),Одиниці,Два,Явищ не було,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,"Молоко пастеризоване жирністю до 2,6% включно",Місячна,1000 г,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,47.71,47.39,47.18,47.10,47.72,47.45,49.20,49.05,49.56,49.95
3,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Судинорозширювальні засоби імпортні,Місячна,"10 табл., капсул",Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,82.99,83.16,83.94,85.89,88.92,95.83,96.36,92.66,89.29,88.39
4,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Сигарети з фільтром медіум класу,Місячна,Пачка (20 шт),Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,111.33,113.69,116.52,119.36,121.91,123.37,126.06,128.15,130.70,133.03
5,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Картопля,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,30.63,31.95,34.73,24.89,21.24,17.93,16.85,15.79,14.76,15.51
6,Середні споживчі ціни на товари (послуги),Не застосовується,Вінницька,Риба морожена,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,190.92,193.71,201.76,202.53,203.39,208.96,211.31,214.37,214.70,224.69
7,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Хліб пшеничний з борошна першого ґатунку,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,45.06,45.38,46.19,46.31,46.39,47.07,47.68,48.26,48.81,49.88
8,Середні споживчі ціни на товари (послуги),Не застосовується,Вінницька,Крупи манні,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,25.38,27.00,28.96,28.96,29.16,29.41,29.12,29.06,28.56,29.09
9,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Газ скраплений для автомобілів,Місячна,Літр,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,35.65,35.03,34.33,34.39,34.31,34.26,34.25,34.48,36.42,38.05

In [12]:
df.tail(10)

,Показник,Базисний період,Територіальний розріз,Тип товарів і послуг,Періодичність,Одиниця виміру,Масштабування,Кількість десяткових знаків,Спеціальне значення даних,Примітки часового ряду,...,2025-M04,2025-M05,2025-M06,2025-M07,2025-M08,2025-M09,2025-M10,2025-M11,2025-M12,2026-M01
2439,Індекс споживчих цін,До попереднього місяця,Севастополь,Ресторани та готелі,Місячна,Відсоток,Одиниці,Один,NaN,1. З 2001 року. 2. За 2014-2021 роки дані наве...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2440,Індекс споживчих цін,До попереднього місяця,Севастополь,Різні товари та послуги,Місячна,Відсоток,Одиниці,Один,NaN,1. З 2001 року. 2. За 2014-2021 роки дані наве...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2441,Індекс споживчих цін,Рік до попереднього року,Україна,Індекс споживчих цін,Річна,Відсоток,Одиниці,Один,NaN,1. З 1993 року. 2. За 2014 рік дані наведено б...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2442,Індекс споживчих цін,Рік до попереднього року,Україна,Охорона здоров’я,Річна,Відсоток,Одиниці,Один,NaN,1. З 2002 року. 2. За 2014 рік дані наведено б...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2443,Індекс споживчих цін,Рік до попереднього року,Україна,"Предмети домашнього вжитку, побутова техніка т...",Річна,Відсоток,Одиниці,Один,NaN,1. З 2002 року. 2. За 2014 рік дані наведено б...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2444,Індекс споживчих цін,Рік до попереднього року,Україна,"Житло, вода, електроенергія, газ та інші види ...",Річна,Відсоток,Одиниці,Один,NaN,1. З 2002 року. 2. За 2014 рік дані наведено б...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2445,Індекс споживчих цін,Рік до попереднього року,Україна,Одяг і взуття,Річна,Відсоток,Одиниці,Один,NaN,1. З 2002 року. 2. За 2014 рік дані наведено б...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2446,Індекс споживчих цін,Рік до попереднього року,Україна,Відпочинок і культура,Річна,Відсоток,Одиниці,Один,NaN,1. З 2002 року. 2. За 2014 рік дані наведено б...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2447,Індекс споживчих цін,Рік до попереднього року,Україна,Зв’язок,Річна,Відсоток,Одиниці,Один,NaN,1. З 2002 року. 2. За 2014 рік дані наведено б...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2448,Індекс споживчих цін,Рік до попереднього року,Україна,Транспорт,Річна,Відсоток,Одиниці,Один,NaN,1. З 2002 року. 2. За 2014 рік дані наведено б...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Залишаємо лише Україну та Середні споживчі ціни на товари (послуги)

In [21]:
df[
    (df['Територіальний розріз'] == 'Україна') &
    (df['Показник'] == 'Середні споживчі ціни на товари (послуги)')
]

,Показник,Базисний період,Територіальний розріз,Тип товарів і послуг,Періодичність,Одиниця виміру,Масштабування,Кількість десяткових знаків,Спеціальне значення даних,Примітки часового ряду,...,2025-M04,2025-M05,2025-M06,2025-M07,2025-M08,2025-M09,2025-M10,2025-M11,2025-M12,2026-M01
0,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Птиця (тушки курячі),Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,98.15,107.22,113.94,115.55,117.95,118.03,119.98,117.93,116.20,112.47
1,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Сигарети без фільтру,Місячна,Пачка (20 шт),Одиниці,Два,Явищ не було,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,"Молоко пастеризоване жирністю до 2,6% включно",Місячна,1000 г,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,47.71,47.39,47.18,47.10,47.72,47.45,49.20,49.05,49.56,49.95
3,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Судинорозширювальні засоби імпортні,Місячна,"10 табл., капсул",Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,82.99,83.16,83.94,85.89,88.92,95.83,96.36,92.66,89.29,88.39
4,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Сигарети з фільтром медіум класу,Місячна,Пачка (20 шт),Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,111.33,113.69,116.52,119.36,121.91,123.37,126.06,128.15,130.70,133.03
5,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Картопля,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,30.63,31.95,34.73,24.89,21.24,17.93,16.85,15.79,14.76,15.51
7,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Хліб пшеничний з борошна першого ґатунку,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,45.06,45.38,46.19,46.31,46.39,47.07,47.68,48.26,48.81,49.88
9,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Газ скраплений для автомобілів,Місячна,Літр,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,35.65,35.03,34.33,34.39,34.31,34.26,34.25,34.48,36.42,38.05
12,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Стоматологічні послуги,Місячна,Одиниця,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,1264.74,1280.71,1297.96,1314.15,1323.65,1332.81,1351.46,1362.90,1379.62,1415.78
13,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Бензин А-92,Місячна,Літр,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,52.29,51.63,53.48,56.35,56.16,55.70,55.90,55.70,55.91,56.69
14,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Борошно пшеничне,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,21.36,21.71,21.71,21.75,21.74,21.82,21.95,21.95,21.89,22.04
15,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Яловичина,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,307.16,314.73,323.18,329.33,332.53,343.79,348.55,349.24,352.21,356.73
16,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Макаронні вироби з м’яких сортів пшениці,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,35.52,35.46,35.69,35.63,35.40,35.56,35.56,36.14,35.95,36.57
17,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Жарознижувальні та знеболювальні препарати імп...,Місячна,1 пакетик,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,33.81,33.86,33.96,34.12,33.75,33.86,34.01,33.39,33.44,33.25
18,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Сметана жирністю до 15% включно,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,137.41,138.58,137.99,138.46,138.83,140.94,142.24,144.43,142.61,144.34
19,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Проїзд у міському транспорті,Місячна,Квиток,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,11.18,11.50,11.84,11.87,11.87,11.92,11.94,11.94,11.94,12.13
22,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Сало,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,167.93,170.84,172.96,174.64,185.03,194.04,206.81,214.12,215.95,216.43
23,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Пиво вітчизняних марок,Місячна,"0,5 л",Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,35.53,36.01,35.96,36.67,36.35,37.33,37.00,37.29,37.24,37.52
24,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Капуста білокачанна,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,49.72,53.48,28.23,21.33,18.14,14.16,12.72,11.16,10.07,10.48
26,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Молочні суміші для дитячого харчування,Місячна,250 г,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,155.03,155.94,156.66,159.38,163.92,165.13,167.56,171.15,174.13,177.50
29,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Крупи ячні,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,21.86,22.35,22.95,23.53,23.46,23.52,23.83,23.87,23.88,24.09
30,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Крупи пшеничні,Місячна,Кілограм,Одиниці,Два,Явищ не було,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,21.58,21.76,21.65,21.88,21.76,21.65,21.95,21.95,21.95,22.06
31,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Яблука,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,46.35,58.04,79.49,85.60,70.31,48.81,42.89,41.86,39.80,41.23
32,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Послуги у сфері страхування особистого транспорту,Місячна,Вартість страхового полісу,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,4696.14,4720.88,4871.48,4985.31,5011.40,5015.99,5057.77,5015.63,5007.86,4990.88
33,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Яйця,Місячна,Десяток,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,59.17,54.21,53.63,54.50,55.78,54.16,60.15,67.67,71.57,66.27
34,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Рис,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,55.25,55.03,54.78,54.96,54.15,53.43,53.28,52.70,51.85,51.61
35,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Вина столові вітчизняні,Місячна,"0,75 л",Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,118.57,118.88,120.07,121.13,120.42,121.11,122.48,124.58,124.73,132.35
36,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Масло вершкове,Місячна,200 г,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,107.98,107.33,107.40,107.65,107.96,109.83,111.42,112.19,111.92,110.52
37,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Антибіотики вітчизняні,Місячна,"10 табл., капсул",Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,70.65,71.93,72.23,72.35,73.16,75.01,75.29,75.41,75.21,74.64
38,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Буряк,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,27.99,35.55,44.80,20.03,12.52,11.22,11.14,10.16,9.25,9.77
39,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Філе куряче,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,184.29,199.76,214.63,218.21,223.89,226.31,228.97,224.52,220.66,218.32
40,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Олія соняшникова,Місячна,Літр,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,80.20,80.61,80.62,81.02,81.43,83.23,84.68,86.02,86.86,87.88
42,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Сигарети з фільтром преміум класу,Місячна,Пачка (20 шт),Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,131.25,133.42,135.21,139.54,142.30,144.13,147.14,150.23,153.06,155.50
43,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Сигарети з фільтром вітчизняних марок,Місячна,Пачка (20 шт),Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,102.38,104.27,106.41,108.70,111.21,113.74,116.90,120.09,122.00,123.48
44,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Судинорозширювальні засоби вітчизняні,Місячна,"10 табл., капсул",Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,18.03,18.03,18.11,18.16,18.20,18.40,18.32,18.31,18.49,18.45
45,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Дошкільна освіта,Місячна,День,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,59.06,60.97,61.54,63.29,63.32,63.00,63.66,63.84,63.82,66.68
46,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Дизельне пальне,Місячна,Літр,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,53.67,52.80,53.41,55.84,55.84,55.76,55.72,57.75,58.63,58.91
47,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Хліб пшеничний з борошна вищого ґатунку,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,56.05,57.17,57.89,58.51,58.63,59.14,59.90,59.93,60.54,61.06
49,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Крупи гречані,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,35.92,35.61,35.17,35.19,35.24,35.99,40.37,42.55,44.88,47.45
50,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,"Хліб житній, житньо-пшеничний",Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,46.56,47.14,47.52,47.99,48.86,49.67,50.22,50.87,51.23,51.75
51,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Бензин А-95,Місячна,Літр,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,55.03,54.53,56.38,58.97,58.84,58.79,58.74,58.72,58.74,59.28
52,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Ковбаси варені першого ґатунку,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,188.34,193.75,196.70,201.47,199.70,206.94,207.47,205.83,205.30,208.25
53,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Батон,Місячна,500 г,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,28.93,29.33,29.39,29.45,29.79,30.04,30.35,30.56,30.82,30.99
55,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Крупи манні,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,28.19,28.43,28.79,29.09,29.37,29.21,29.41,29.21,29.39,29.35
56,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Жарознижувальні та знеболювальні препарати віт...,Місячна,10 табл.,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,26.09,26.65,26.69,26.69,27.25,27.42,27.52,27.17,27.75,27.64
58,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Горілка,Місячна,"0,5 л",Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,118.42,118.14,119.56,119.85,118.35,118.70,120.76,120.56,121.52,121.64
64,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Цукор,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,33.41,33.58,33.60,32.68,32.36,31.86,31.06,30.37,29.70,29.38
66,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Пшоно,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,25.90,25.84,25.68,25.93,26.46,27.32,29.06,30.80,33.57,35.55
68,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Плата за оренду 1-кімнатної квартири,Місячна,Місяць,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,7446.44,7504.07,7541.34,7583.76,7711.52,7815.78,7878.83,7952.41,7986.20,8066.72
69,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Сири м’які жирні,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,225.46,226.12,225.78,228.41,228.36,229.02,231.51,236.73,238.22,241.17
71,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Антибіотики імпортні,Місячна,"10 табл., капсул",Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,283.28,289.29,289.00,289.71,291.51,296.05,296.32,296.32,295.99,289.05
72,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Свинина,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,212.72,230.01,238.38,241.93,248.93,251.80,253.06,242.97,237.10,230.12
73,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Морква,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,38.96,43.34,49.69,30.86,17.04,13.27,12.66,11.47,10.61,11.55
74,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Цибуля ріпчаста,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,19.25,30.15,31.28,17.28,16.28,13.06,10.86,9.19,8.36,8.87
75,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Риба морожена,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,...,191.22,194.10,196.77,198.43,201.65,206.77,211.51,217.96,218.30,221.83