<a href="https://colab.research.google.com/github/arcctg/kpi-ml-lab1/blob/main/task_1_ukrstat_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Імпорт бібліотек.** Підключаємо все необхідне для обробки даних, візуалізації та статистики: pandas (таблиці), numpy (масиви), matplotlib і seaborn (графіки), statistics (mean, median, mode, variance, std), re (регулярні вирази для фільтрації колонок за шаблоном, наприклад YYYY-M01).

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics
import re

**Завантаження датасету.** Читаємо CSV через `pd.read_csv(url)` закинутий в гітхаб репо для зручності. Джерело — Держстат (ukrstat.gov.ua). Датасет містить місячні споживчі ціни на товари та послуги в Україні з 1991 року. Використовуємо try/except для обробки помилок при завантаженні.

In [28]:
url = 'https://raw.githubusercontent.com/arcctg/kpi-ml-lab1/main/ukrstat_prices.csv'

try:
    df = pd.read_csv(url)
    print("Data was loaded successfully:")
    display(df.head())
except Exception as e:
    print(f"Error on load: {e}")

Data was loaded successfully:

,Показник,Базисний період,Територіальний розріз,Тип товарів і послуг,Періодичність,Одиниця виміру,Масштабування,Кількість десяткових знаків,Спеціальне значення даних,Примітки часового ряду,Примітки спостереження,1991,1991-M01,1991-M02,1991-M03,1991-M04,1991-M05,1991-M06,1991-M07,1991-M08,1991-M09,1991-M10,1991-M11,1991-M12,1992,1992-M01,1992-M02,1992-M03,1992-M04,1992-M05,1992-M06,1992-M07,1992-M08,1992-M09,1992-M10,1992-M11,1992-M12,1993,1993-M01,1993-M02,1993-M03,1993-M04,1993-M05,1993-M06,1993-M07,1993-M08,1993-M09,1993-M10,1993-M11,1993-M12,1994,1994-M01,1994-M02,1994-M03,1994-M04,1994-M05,1994-M06,1994-M07,1994-M08,1994-M09,1994-M10,1994-M11,1994-M12,1995,1995-M01,1995-M02,1995-M03,1995-M04,1995-M05,1995-M06,1995-M07,1995-M08,1995-M09,1995-M10,1995-M11,1995-M12,1996,1996-M01,1996-M02,1996-M03,1996-M04,1996-M05,1996-M06,1996-M07,1996-M08,1996-M09,1996-M10,1996-M11,1996-M12,1997,1997-M01,1997-M02,1997-M03,1997-M04,1997-M05,1997-M06,1997-M07,1997-M08,1997-M09,1997-M10,1997-M11,1997-M12,1998,1998-M01,1998-M02,1998-M03,1998-M04,1998-M05,1998-M06,1998-M07,1998-M08,1998-M09,1998-M10,1998-M11,1998-M12,1999,1999-M01,1999-M02,1999-M03,1999-M04,1999-M05,1999-M06,1999-M07,1999-M08,1999-M09,1999-M10,1999-M11,1999-M12,2000,2000-M01,2000-M02,2000-M03,2000-M04,2000-M05,2000-M06,2000-M07,2000-M08,2000-M09,2000-M10,2000-M11,2000-M12,2001,2001-M01,2001-M02,2001-M03,2001-M04,2001-M05,2001-M06,2001-M07,2001-M08,2001-M09,2001-M10,2001-M11,2001-M12,2002,2002-M01,2002-M02,2002-M03,2002-M04,2002-M05,2002-M06,2002-M07,2002-M08,2002-M09,2002-M10,2002-M11,2002-M12,2003,2003-M01,2003-M02,2003-M03,2003-M04,2003-M05,2003-M06,2003-M07,2003-M08,2003-M09,2003-M10,2003-M11,2003-M12,2004,2004-M01,2004-M02,2004-M03,2004-M04,2004-M05,2004-M06,2004-M07,2004-M08,2004-M09,2004-M10,2004-M11,2004-M12,2005,2005-M01,2005-M02,2005-M03,2005-M04,2005-M05,2005-M06,2005-M07,2005-M08,2005-M09,2005-M10,2005-M11,2005-M12,2006,2006-M01,2006-M02,2006-M03,2006-M04,2006-M05,2006-M06,2006-M07,2006-M08,2006-M09,2006-M10,2006-M11,2006-M12,2007,2007-M01,2007-M02,2007-M03,2007-M04,2007-M05,2007-M06,2007-M07,2007-M08,2007-M09,2007-M10,2007-M11,2007-M12,2008,2008-M01,2008-M02,2008-M03,2008-M04,2008-M05,2008-M06,2008-M07,2008-M08,2008-M09,2008-M10,2008-M11,2008-M12,2009,2009-M01,2009-M02,2009-M03,2009-M04,2009-M05,2009-M06,2009-M07,2009-M08,2009-M09,2009-M10,2009-M11,2009-M12,2010,2010-M01,2010-M02,2010-M03,2010-M04,2010-M05,2010-M06,2010-M07,2010-M08,2010-M09,2010-M10,2010-M11,2010-M12,2011,2011-M01,2011-M02,2011-M03,2011-M04,2011-M05,2011-M06,2011-M07,2011-M08,2011-M09,2011-M10,2011-M11,2011-M12,2012,2012-M01,2012-M02,2012-M03,2012-M04,2012-M05,2012-M06,2012-M07,2012-M08,2012-M09,2012-M10,2012-M11,2012-M12,2013,2013-M01,2013-M02,2013-M03,2013-M04,2013-M05,2013-M06,2013-M07,2013-M08,2013-M09,2013-M10,2013-M11,2013-M12,2014,2014-M01,2014-M02,2014-M03,2014-M04,2014-M05,2014-M06,2014-M07,2014-M08,2014-M09,2014-M10,2014-M11,2014-M12,2015,2015-M01,2015-M02,2015-M03,2015-M04,2015-M05,2015-M06,2015-M07,2015-M08,2015-M09,2015-M10,2015-M11,2015-M12,2016,2016-M01,2016-M02,2016-M03,2016-M04,2016-M05,2016-M06,2016-M07,2016-M08,2016-M09,2016-M10,2016-M11,2016-M12,2017,2017-M01,2017-M02,2017-M03,2017-M04,2017-M05,2017-M06,2017-M07,2017-M08,2017-M09,2017-M10,2017-M11,2017-M12,2018,2018-M01,2018-M02,2018-M03,2018-M04,2018-M05,2018-M06,2018-M07,2018-M08,2018-M09,2018-M10,2018-M11,2018-M12,2019,2019-M01,2019-M02,2019-M03,2019-M04,2019-M05,2019-M06,2019-M07,2019-M08,2019-M09,2019-M10,2019-M11,2019-M12,2020,2020-M01,2020-M02,2020-M03,2020-M04,2020-M05,2020-M06,2020-M07,2020-M08,2020-M09,2020-M10,2020-M11,2020-M12,2021,2021-M01,2021-M02,2021-M03,2021-M04,2021-M05,2021-M06,2021-M07,2021-M08,2021-M09,2021-M10,2021-M11,2021-M12,2022,2022-M01,2022-M02,2022-M03,2022-M04,2022-M05,2022-M06,2022-M07,2022-M08,2022-M09,2022-M10,2022-M11,2022-M12,2023,2023-M01,2023-M02,2023-M03,2023-M04,2023-M05,2023-M06,2023-M07,2023-M08,2023-M09,2023-M10,2023-M11,2023-M12,2024,2024-M01,2024-M02,2024-M03,2024-M04,2024-M05,2024-M06,2024-M07,2024-M08,2024-M09,2024-M10,2024-M11,2024-M12,2025,2025-M01,2025-M02,2025-M03,2025-M04,2025-M05,2025-M06,2025-M07,2025-M08,2025-M09,2025-M10,2025-M11,2025-M12,2026-M01
0,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Птиця (тушки курячі),Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.12,42.70,42.95,43.83,44.45,45.35,49.85,53.94,55.50,55.26,53.95,53.90,NaN,54.86,53.72,54.08,55.17,54.81,54.78,54.90,55.69,58.62,58.64,58.32,57.83,NaN,58.66,58.15,58.32,58.40,59.37,60.22,61.78,62.22,62.27,62.07,60.74,59.37,NaN,58.23,55.09,54.12,52.22,49.59,50.50,51.25,52.18,52.93,54.38,55.17,55.96,NaN,57.40,60.13,63.06,65.35,67.25,68.19,69.34,69.94,71.40,72.42,71.02,70.82,NaN,73.52,74.12,76.19,76.04,74.81,79.54,80.83,82.43,82.43,82.96,80.49,81.29,NaN,82.45,84.63,86.71,87.67,87.56,88.69,90.37,91.43,91.50,91.67,91.27,90.25,NaN,89.92,88.31,87.89,88.03,89.28,87.35,86.76,86.79,90.95,92.22,92.38,92.55,NaN,91.45,91.85,94.95,98.15,107.22,113.94,115.55,117.95,118.03,119.98,117.93,116.20,112.47
1,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Сигарети без фільтру,Місячна,Пачка (20 шт),Одиниці,Два,Явищ не було,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.40,15.85,16.21,16.67,17.39,18.12,18.69,19.09,19.57,20.03,20.19,20.32,NaN,20.66,21.10,21.48,21.94,22.67,23.00,23.36,23.60,23.90,24.27,24.53,25.00,NaN,25.57,25.96,26.26,26.83,27.25,27.76,28.45,29.05,29.53,30.20,30.72,31.27,NaN,32.61,33.40,34.05,34.85,35.44,35.64,36.08,36.45,37.04,37.68,38.21,38.73,NaN,39.35,39.83,40.33,41.58,42.27,42.87,43.49,43.87,44.14,44.77,44.87,45.38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,"Молоко пастеризоване жирністю до 2,6% включно",Місячна,1000 г,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.93,18.58,19.04,19.26,19.35,19.29,19.40,19.61,19.95,20.70,21.27,21.77,NaN,22.01,21.95,22.13,22.03,22.13,22.02,21.90,21.99,22.36,22.85,23.39,23.73,NaN,23.87,24.13,24.18,24.32,24.25,24.15,24.23,24.43,24.73,25.14,25.22,25.31,NaN,24.91,24.99,25.00,25.01,25.09,24.95,24.91,24.83,25.00,25.19,25.39,25.60,NaN,25.41,25.83,25.96,25.99,26.44,26.42,26.50,26.62,27.20,27.63,27.96,28.55,NaN,28.93,29.37,30.53,31.46,31.92,32.29,32.61,32.40,32.90,33.27,33.86,34.28,NaN,35.24,35.42,35.90,35.69,35.66,35.78,36.10,36.33,36.23,36.63,37.09,37.69,NaN,38.15,38.70,38.98,39.41,38.65,38.73,39.01,39.40,40.13,41.62,43.71,45.64,NaN,45.89,46.25,47.15,47.71,47.39,47.18,47.10,47.72,47.45,49.20,49.05,49.56,49.95
3,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Судинорозширювальні засоби імпортні,Місячна,"10 табл., капсул",Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.91,44.11,44.41,44.66,44.95,45.00,44.96,45.08,45.17,45.31,45.59,46.07,NaN,46.48,46.31,46.33,46.34,46.53,46.07,46.03,47.05,47.60,47.95,48.00,47.93,NaN,48.47,48.73,48.68,48.66,48.49,48.43,48.27,48.18,47.95,47.86,48.01,47.73,NaN,47.00,46.77,47.40,48.95,49.24,49.08,49.51,50.36,50.80,51.03,52.15,52.73,NaN,53.09,53.33,53.85,54.61,54.88,54.95,54.72,54.61,54.60,55.12,54.88,54.96,NaN,53.35,53.97,58.59,61.60,60.63,60.47,60.07,63.01,64.25,65.05,65.71,66.11,NaN,66.62,66.56,66.83,68.04,69.21,69.41,69.20,69.44,69.24,69.04,68.87,70.23,NaN,70.81,71.26,72.12,72.80,73.43,74.26,75.15,76.00,77.50,78.54,78.64,79.49,NaN,81.03,81.79,83.32,82.99,83.16,83.94,85.89,88.92,95.83,96.36,92.66,89.29,88.39
4,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Сигарети з фільтром медіум класу,Місячна,Пачка (20 шт),Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.30,20.01,20.52,21.02,22.30,23.57,24.48,25.14,25.59,25.93,26.07,26.29,NaN,26.86,27.61,28.09,28.76,29.39,30.15,31.00,31.47,31.89,32.41,32.81,33.39,NaN,34.10,34.70,35.26,35.90,36.59,37.24,37.86,38.35,39.01,39.54,40.10,40.72,NaN,41.41,42.01,42.63,43.44,44.28,44.81,45.38,46.00,46.85,48.00,48.91,49.91,NaN,51.55,52.34,52.90,54.28,55.09,55.72,56.19,56.54,57.25,57.79,58.44,59.03,NaN,58.97,59.77,60.68,62.56,63.41,64.43,65.55,66.75,67.49,68.32,69.05,69.90,NaN,70.29,71.36,71.97,72.81,73.86,74.85,76.06,77.49,78.88,79.91,80.66,81.40,NaN,82.31,83.50,84.86,85.92,87.14,88.71,89.96,90.76,93.50,96.16,98.28,101.80,NaN,104.30,106.54,108.58,111.33,113.69,116.52,119.36,121.91,123.37,126.06,128.15,130.70,133.03

**Розмір датасету.** Виклик `df.shape` показує 2449 рядків × 467 колонок. Даних занадто багато (різні території, показники, період 1991–2026), тому обмежуємо вибірку як частина первинної обробки.

In [29]:
df.shape

(2449, 467)

**Огляд структури.** Методи `head(10)` і `tail(10)` показують початок і кінець таблиці. Бачимо територія (Україна загалом і області), показники (середні ціни та індекси), типи товарів, числові колонки з роками та місяцями. Це допомагає визначити умови фільтрації.

In [30]:
df.head(10)

,Показник,Базисний період,Територіальний розріз,Тип товарів і послуг,Періодичність,Одиниця виміру,Масштабування,Кількість десяткових знаків,Спеціальне значення даних,Примітки часового ряду,Примітки спостереження,1991,1991-M01,1991-M02,1991-M03,1991-M04,1991-M05,1991-M06,1991-M07,1991-M08,1991-M09,1991-M10,1991-M11,1991-M12,1992,1992-M01,1992-M02,1992-M03,1992-M04,1992-M05,1992-M06,1992-M07,1992-M08,1992-M09,1992-M10,1992-M11,1992-M12,1993,1993-M01,1993-M02,1993-M03,1993-M04,1993-M05,1993-M06,1993-M07,1993-M08,1993-M09,1993-M10,1993-M11,1993-M12,1994,1994-M01,1994-M02,1994-M03,1994-M04,1994-M05,1994-M06,1994-M07,1994-M08,1994-M09,1994-M10,1994-M11,1994-M12,1995,1995-M01,1995-M02,1995-M03,1995-M04,1995-M05,1995-M06,1995-M07,1995-M08,1995-M09,1995-M10,1995-M11,1995-M12,1996,1996-M01,1996-M02,1996-M03,1996-M04,1996-M05,1996-M06,1996-M07,1996-M08,1996-M09,1996-M10,1996-M11,1996-M12,1997,1997-M01,1997-M02,1997-M03,1997-M04,1997-M05,1997-M06,1997-M07,1997-M08,1997-M09,1997-M10,1997-M11,1997-M12,1998,1998-M01,1998-M02,1998-M03,1998-M04,1998-M05,1998-M06,1998-M07,1998-M08,1998-M09,1998-M10,1998-M11,1998-M12,1999,1999-M01,1999-M02,1999-M03,1999-M04,1999-M05,1999-M06,1999-M07,1999-M08,1999-M09,1999-M10,1999-M11,1999-M12,2000,2000-M01,2000-M02,2000-M03,2000-M04,2000-M05,2000-M06,2000-M07,2000-M08,2000-M09,2000-M10,2000-M11,2000-M12,2001,2001-M01,2001-M02,2001-M03,2001-M04,2001-M05,2001-M06,2001-M07,2001-M08,2001-M09,2001-M10,2001-M11,2001-M12,2002,2002-M01,2002-M02,2002-M03,2002-M04,2002-M05,2002-M06,2002-M07,2002-M08,2002-M09,2002-M10,2002-M11,2002-M12,2003,2003-M01,2003-M02,2003-M03,2003-M04,2003-M05,2003-M06,2003-M07,2003-M08,2003-M09,2003-M10,2003-M11,2003-M12,2004,2004-M01,2004-M02,2004-M03,2004-M04,2004-M05,2004-M06,2004-M07,2004-M08,2004-M09,2004-M10,2004-M11,2004-M12,2005,2005-M01,2005-M02,2005-M03,2005-M04,2005-M05,2005-M06,2005-M07,2005-M08,2005-M09,2005-M10,2005-M11,2005-M12,2006,2006-M01,2006-M02,2006-M03,2006-M04,2006-M05,2006-M06,2006-M07,2006-M08,2006-M09,2006-M10,2006-M11,2006-M12,2007,2007-M01,2007-M02,2007-M03,2007-M04,2007-M05,2007-M06,2007-M07,2007-M08,2007-M09,2007-M10,2007-M11,2007-M12,2008,2008-M01,2008-M02,2008-M03,2008-M04,2008-M05,2008-M06,2008-M07,2008-M08,2008-M09,2008-M10,2008-M11,2008-M12,2009,2009-M01,2009-M02,2009-M03,2009-M04,2009-M05,2009-M06,2009-M07,2009-M08,2009-M09,2009-M10,2009-M11,2009-M12,2010,2010-M01,2010-M02,2010-M03,2010-M04,2010-M05,2010-M06,2010-M07,2010-M08,2010-M09,2010-M10,2010-M11,2010-M12,2011,2011-M01,2011-M02,2011-M03,2011-M04,2011-M05,2011-M06,2011-M07,2011-M08,2011-M09,2011-M10,2011-M11,2011-M12,2012,2012-M01,2012-M02,2012-M03,2012-M04,2012-M05,2012-M06,2012-M07,2012-M08,2012-M09,2012-M10,2012-M11,2012-M12,2013,2013-M01,2013-M02,2013-M03,2013-M04,2013-M05,2013-M06,2013-M07,2013-M08,2013-M09,2013-M10,2013-M11,2013-M12,2014,2014-M01,2014-M02,2014-M03,2014-M04,2014-M05,2014-M06,2014-M07,2014-M08,2014-M09,2014-M10,2014-M11,2014-M12,2015,2015-M01,2015-M02,2015-M03,2015-M04,2015-M05,2015-M06,2015-M07,2015-M08,2015-M09,2015-M10,2015-M11,2015-M12,2016,2016-M01,2016-M02,2016-M03,2016-M04,2016-M05,2016-M06,2016-M07,2016-M08,2016-M09,2016-M10,2016-M11,2016-M12,2017,2017-M01,2017-M02,2017-M03,2017-M04,2017-M05,2017-M06,2017-M07,2017-M08,2017-M09,2017-M10,2017-M11,2017-M12,2018,2018-M01,2018-M02,2018-M03,2018-M04,2018-M05,2018-M06,2018-M07,2018-M08,2018-M09,2018-M10,2018-M11,2018-M12,2019,2019-M01,2019-M02,2019-M03,2019-M04,2019-M05,2019-M06,2019-M07,2019-M08,2019-M09,2019-M10,2019-M11,2019-M12,2020,2020-M01,2020-M02,2020-M03,2020-M04,2020-M05,2020-M06,2020-M07,2020-M08,2020-M09,2020-M10,2020-M11,2020-M12,2021,2021-M01,2021-M02,2021-M03,2021-M04,2021-M05,2021-M06,2021-M07,2021-M08,2021-M09,2021-M10,2021-M11,2021-M12,2022,2022-M01,2022-M02,2022-M03,2022-M04,2022-M05,2022-M06,2022-M07,2022-M08,2022-M09,2022-M10,2022-M11,2022-M12,2023,2023-M01,2023-M02,2023-M03,2023-M04,2023-M05,2023-M06,2023-M07,2023-M08,2023-M09,2023-M10,2023-M11,2023-M12,2024,2024-M01,2024-M02,2024-M03,2024-M04,2024-M05,2024-M06,2024-M07,2024-M08,2024-M09,2024-M10,2024-M11,2024-M12,2025,2025-M01,2025-M02,2025-M03,2025-M04,2025-M05,2025-M06,2025-M07,2025-M08,2025-M09,2025-M10,2025-M11,2025-M12,2026-M01
0,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Птиця (тушки курячі),Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.12,42.70,42.95,43.83,44.45,45.35,49.85,53.94,55.50,55.26,53.95,53.90,NaN,54.86,53.72,54.08,55.17,54.81,54.78,54.90,55.69,58.62,58.64,58.32,57.83,NaN,58.66,58.15,58.32,58.40,59.37,60.22,61.78,62.22,62.27,62.07,60.74,59.37,NaN,58.23,55.09,54.12,52.22,49.59,50.50,51.25,52.18,52.93,54.38,55.17,55.96,NaN,57.40,60.13,63.06,65.35,67.25,68.19,69.34,69.94,71.40,72.42,71.02,70.82,NaN,73.52,74.12,76.19,76.04,74.81,79.54,80.83,82.43,82.43,82.96,80.49,81.29,NaN,82.45,84.63,86.71,87.67,87.56,88.69,90.37,91.43,91.50,91.67,91.27,90.25,NaN,89.92,88.31,87.89,88.03,89.28,87.35,86.76,86.79,90.95,92.22,92.38,92.55,NaN,91.45,91.85,94.95,98.15,107.22,113.94,115.55,117.95,118.03,119.98,117.93,116.20,112.47
1,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Сигарети без фільтру,Місячна,Пачка (20 шт),Одиниці,Два,Явищ не було,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.40,15.85,16.21,16.67,17.39,18.12,18.69,19.09,19.57,20.03,20.19,20.32,NaN,20.66,21.10,21.48,21.94,22.67,23.00,23.36,23.60,23.90,24.27,24.53,25.00,NaN,25.57,25.96,26.26,26.83,27.25,27.76,28.45,29.05,29.53,30.20,30.72,31.27,NaN,32.61,33.40,34.05,34.85,35.44,35.64,36.08,36.45,37.04,37.68,38.21,38.73,NaN,39.35,39.83,40.33,41.58,42.27,42.87,43.49,43.87,44.14,44.77,44.87,45.38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,"Молоко пастеризоване жирністю до 2,6% включно",Місячна,1000 г,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.93,18.58,19.04,19.26,19.35,19.29,19.40,19.61,19.95,20.70,21.27,21.77,NaN,22.01,21.95,22.13,22.03,22.13,22.02,21.90,21.99,22.36,22.85,23.39,23.73,NaN,23.87,24.13,24.18,24.32,24.25,24.15,24.23,24.43,24.73,25.14,25.22,25.31,NaN,24.91,24.99,25.00,25.01,25.09,24.95,24.91,24.83,25.00,25.19,25.39,25.60,NaN,25.41,25.83,25.96,25.99,26.44,26.42,26.50,26.62,27.20,27.63,27.96,28.55,NaN,28.93,29.37,30.53,31.46,31.92,32.29,32.61,32.40,32.90,33.27,33.86,34.28,NaN,35.24,35.42,35.90,35.69,35.66,35.78,36.10,36.33,36.23,36.63,37.09,37.69,NaN,38.15,38.70,38.98,39.41,38.65,38.73,39.01,39.40,40.13,41.62,43.71,45.64,NaN,45.89,46.25,47.15,47.71,47.39,47.18,47.10,47.72,47.45,49.20,49.05,49.56,49.95
3,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Судинорозширювальні засоби імпортні,Місячна,"10 табл., капсул",Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.91,44.11,44.41,44.66,44.95,45.00,44.96,45.08,45.17,45.31,45.59,46.07,NaN,46.48,46.31,46.33,46.34,46.53,46.07,46.03,47.05,47.60,47.95,48.00,47.93,NaN,48.47,48.73,48.68,48.66,48.49,48.43,48.27,48.18,47.95,47.86,48.01,47.73,NaN,47.00,46.77,47.40,48.95,49.24,49.08,49.51,50.36,50.80,51.03,52.15,52.73,NaN,53.09,53.33,53.85,54.61,54.88,54.95,54.72,54.61,54.60,55.12,54.88,54.96,NaN,53.35,53.97,58.59,61.60,60.63,60.47,60.07,63.01,64.25,65.05,65.71,66.11,NaN,66.62,66.56,66.83,68.04,69.21,69.41,69.20,69.44,69.24,69.04,68.87,70.23,NaN,70.81,71.26,72.12,72.80,73.43,74.26,75.15,76.00,77.50,78.54,78.64,79.49,NaN,81.03,81.79,83.32,82.99,83.16,83.94,85.89,88.92,95.83,96.36,92.66,89.29,88.39
4,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Сигарети з фільтром медіум класу,Місячна,Пачка (20 шт),Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.30,20.01,20.52,21.02,22.30,23.57,24.48,25.14,25.59,25.93,26.07,26.29,NaN,26.86,27.61,28.09,28.76,29.39,30.15,31.00,31.47,31.89,32.41,32.81,33.39,NaN,34.10,34.70,35.26,35.90,36.59,37.24,37.86,38.35,39.01,39.54,40.10,40.72,NaN,41.41,42.01,42.63,43.44,44.28,44.81,45.38,46.00,46.85,48.00,48.91,49.91,NaN,51.55,52.34,52.90,54.28,55.09,55.72,56.19,56.54,57.25,57.79,58.44,59.03,NaN,58.97,59.77,60.68,62.56,63.41,64.43,65.55,66.75,67.49,68.32,69.05,69.90,NaN,70.29,71.36,71.97,72.81,73.86,74.85,76.06,77.49,78.88,79.91,80.66,81.40,NaN,82.31,83.50,84.86,85.92,87.14,88.71,89.96,90.76,93.50,96.16,98.28,101.80,NaN,104.30,106.54,108.58,111.33,113.69,116.52,119.36,121.91,123.37,126.06,128.15,130.70,133.03
5,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Картопля,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.58,6.11,6.25,6.71,8.36,11.12,8.99,7.44,6.76,6.19,5.95,6.00,NaN,6.43,6.89,7.58,7.83,7.54,8.73,7.95,7.56,6.86,6.52,6.76,7.99,NaN,9.33,10.09,10.16,10.73,14.07,17.26,15.30,15.02,14.63,15.29,14.14,13.52,NaN,13.13,12.80,12.89,14.75,15.27,16.06,12.67,10.02,9.08,8.96,9.23,10.15,NaN,11.14,11.87,12.17,11.92,11.96,13.30,11.79,8.66,8.32,8.69,8.61,8.76,NaN,9.29,9.54,11.70,10.23,9.64,12.24,18.93,13.56,10.84,9.91,9.13,9.20,NaN,9.40,9.57,9.55,9.49,9.89,12.04,20.25,12.87,10.95,10.16,11.90,15.13,NaN,21.46,22.75,22.73,22.45,24.53,28.39,20.08,19.73,20.67,25.85,29.79,29.74,NaN,30.09,29.87,30.12,30.63,31.95,34.73,24.89,21.24,17.93,16.85,15.79,14.76,15.51
6,Середні споживчі ціни на товари (послуги),Не застосовується,Вінницька,Риба морожена,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.38,71.25,71.65,71.62,71.79,71.87,73.01,71.40,71.42,71.32,70.48,70.42,NaN,67.08,66.05,67.00,69.30,70.60,70.41,71.14,71.71,72.71,74.09,74.15,74.09,NaN,75.28,75.77,76.06,77.09,75.55,77.67,78.20,78.65,79.77,79.12,81.28,81.40,NaN,78.24,77.37,77.68,77.68,79.01,79.05,78.39,77.84,79.89,80.10,79.23,78.15,NaN,78.17,78.58,80.27,83.33,82.12,82.49,83.34,82.67,82.49,84.28,85.95,86.40,NaN,114.22,114.16,119.12,128.12,129.58,133.31,131.38,138.56,141.59,154.50,156.43,160.91,NaN,166.16,166.96,167.03,169.12,170.00,170.15,171.44,173.13,172.54,172.98,173.59,172.28,NaN,169.61,168.67,169.55,170.59,169.28,171.55,173.82,174.67,174.59,179.30,181.25,184.56,NaN,183.48,187.34,188.33,190.92,193.71,201.76,202.53,203.39,208.96,211.31,214.37,214.70,224.69

In [31]:
df.tail(10)

,Показник,Базисний період,Територіальний розріз,Тип товарів і послуг,Періодичність,Одиниця виміру,Масштабування,Кількість десяткових знаків,Спеціальне значення даних,Примітки часового ряду,Примітки спостереження,1991,1991-M01,1991-M02,1991-M03,1991-M04,1991-M05,1991-M06,1991-M07,1991-M08,1991-M09,1991-M10,1991-M11,1991-M12,1992,1992-M01,1992-M02,1992-M03,1992-M04,1992-M05,1992-M06,1992-M07,1992-M08,1992-M09,1992-M10,1992-M11,1992-M12,1993,1993-M01,1993-M02,1993-M03,1993-M04,1993-M05,1993-M06,1993-M07,1993-M08,1993-M09,1993-M10,1993-M11,1993-M12,1994,1994-M01,1994-M02,1994-M03,1994-M04,1994-M05,1994-M06,1994-M07,1994-M08,1994-M09,1994-M10,1994-M11,1994-M12,1995,1995-M01,1995-M02,1995-M03,1995-M04,1995-M05,1995-M06,1995-M07,1995-M08,1995-M09,1995-M10,1995-M11,1995-M12,1996,1996-M01,1996-M02,1996-M03,1996-M04,1996-M05,1996-M06,1996-M07,1996-M08,1996-M09,1996-M10,1996-M11,1996-M12,1997,1997-M01,1997-M02,1997-M03,1997-M04,1997-M05,1997-M06,1997-M07,1997-M08,1997-M09,1997-M10,1997-M11,1997-M12,1998,1998-M01,1998-M02,1998-M03,1998-M04,1998-M05,1998-M06,1998-M07,1998-M08,1998-M09,1998-M10,1998-M11,1998-M12,1999,1999-M01,1999-M02,1999-M03,1999-M04,1999-M05,1999-M06,1999-M07,1999-M08,1999-M09,1999-M10,1999-M11,1999-M12,2000,2000-M01,2000-M02,2000-M03,2000-M04,2000-M05,2000-M06,2000-M07,2000-M08,2000-M09,2000-M10,2000-M11,2000-M12,2001,2001-M01,2001-M02,2001-M03,2001-M04,2001-M05,2001-M06,2001-M07,2001-M08,2001-M09,2001-M10,2001-M11,2001-M12,2002,2002-M01,2002-M02,2002-M03,2002-M04,2002-M05,2002-M06,2002-M07,2002-M08,2002-M09,2002-M10,2002-M11,2002-M12,2003,2003-M01,2003-M02,2003-M03,2003-M04,2003-M05,2003-M06,2003-M07,2003-M08,2003-M09,2003-M10,2003-M11,2003-M12,2004,2004-M01,2004-M02,2004-M03,2004-M04,2004-M05,2004-M06,2004-M07,2004-M08,2004-M09,2004-M10,2004-M11,2004-M12,2005,2005-M01,2005-M02,2005-M03,2005-M04,2005-M05,2005-M06,2005-M07,2005-M08,2005-M09,2005-M10,2005-M11,2005-M12,2006,2006-M01,2006-M02,2006-M03,2006-M04,2006-M05,2006-M06,2006-M07,2006-M08,2006-M09,2006-M10,2006-M11,2006-M12,2007,2007-M01,2007-M02,2007-M03,2007-M04,2007-M05,2007-M06,2007-M07,2007-M08,2007-M09,2007-M10,2007-M11,2007-M12,2008,2008-M01,2008-M02,2008-M03,2008-M04,2008-M05,2008-M06,2008-M07,2008-M08,2008-M09,2008-M10,2008-M11,2008-M12,2009,2009-M01,2009-M02,2009-M03,2009-M04,2009-M05,2009-M06,2009-M07,2009-M08,2009-M09,2009-M10,2009-M11,2009-M12,2010,2010-M01,2010-M02,2010-M03,2010-M04,2010-M05,2010-M06,2010-M07,2010-M08,2010-M09,2010-M10,2010-M11,2010-M12,2011,2011-M01,2011-M02,2011-M03,2011-M04,2011-M05,2011-M06,2011-M07,2011-M08,2011-M09,2011-M10,2011-M11,2011-M12,2012,2012-M01,2012-M02,2012-M03,2012-M04,2012-M05,2012-M06,2012-M07,2012-M08,2012-M09,2012-M10,2012-M11,2012-M12,2013,2013-M01,2013-M02,2013-M03,2013-M04,2013-M05,2013-M06,2013-M07,2013-M08,2013-M09,2013-M10,2013-M11,2013-M12,2014,2014-M01,2014-M02,2014-M03,2014-M04,2014-M05,2014-M06,2014-M07,2014-M08,2014-M09,2014-M10,2014-M11,2014-M12,2015,2015-M01,2015-M02,2015-M03,2015-M04,2015-M05,2015-M06,2015-M07,2015-M08,2015-M09,2015-M10,2015-M11,2015-M12,2016,2016-M01,2016-M02,2016-M03,2016-M04,2016-M05,2016-M06,2016-M07,2016-M08,2016-M09,2016-M10,2016-M11,2016-M12,2017,2017-M01,2017-M02,2017-M03,2017-M04,2017-M05,2017-M06,2017-M07,2017-M08,2017-M09,2017-M10,2017-M11,2017-M12,2018,2018-M01,2018-M02,2018-M03,2018-M04,2018-M05,2018-M06,2018-M07,2018-M08,2018-M09,2018-M10,2018-M11,2018-M12,2019,2019-M01,2019-M02,2019-M03,2019-M04,2019-M05,2019-M06,2019-M07,2019-M08,2019-M09,2019-M10,2019-M11,2019-M12,2020,2020-M01,2020-M02,2020-M03,2020-M04,2020-M05,2020-M06,2020-M07,2020-M08,2020-M09,2020-M10,2020-M11,2020-M12,2021,2021-M01,2021-M02,2021-M03,2021-M04,2021-M05,2021-M06,2021-M07,2021-M08,2021-M09,2021-M10,2021-M11,2021-M12,2022,2022-M01,2022-M02,2022-M03,2022-M04,2022-M05,2022-M06,2022-M07,2022-M08,2022-M09,2022-M10,2022-M11,2022-M12,2023,2023-M01,2023-M02,2023-M03,2023-M04,2023-M05,2023-M06,2023-M07,2023-M08,2023-M09,2023-M10,2023-M11,2023-M12,2024,2024-M01,2024-M02,2024-M03,2024-M04,2024-M05,2024-M06,2024-M07,2024-M08,2024-M09,2024-M10,2024-M11,2024-M12,2025,2025-M01,2025-M02,2025-M03,2025-M04,2025-M05,2025-M06,2025-M07,2025-M08,2025-M09,2025-M10,2025-M11,2025-M12,2026-M01
2439,Індекс споживчих цін,До попереднього місяця,Севастополь,Ресторани та готелі,Місячна,Відсоток,Одиниці,Один,NaN,1. З 2001 року. 2. За 2014-2021 роки дані наве...,Виключні події та обставини.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,100.3,100.0,100.0,102.1,101.2,103.7,104.1,99.4,102.2,100.5,102.5,NaN,103.6,101.4,100.7,104.2,106.6,101.5,102.6,100.5,100.8,99.6,101.4,100.7,NaN,100.9,101.3,100.4,100.7,100.6,101.4,101.6,102.3,98.8,99.3,99.6,95.6,NaN,100.2,100.8,99.9,100.7,103.4,102.8,101.7,101.9,98.3,100.2,99.8,100.0,NaN,99.6,100.0,101.1,103.6,103.4,102.7,101.4,101.0,99.3,97.7,100.0,100.2,NaN,100.3,99.6,100.2,101.2,102.1,100.8,102.8,99.6,98.3,97.5,100.5,100.4,NaN,101.4,99.9,101.0,99.8,101.1,102.5,102.4,100.6,99.0,98.2,100.0,98.7,NaN,101.1,98.8,101.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2440,Індекс споживчих цін,До попереднього місяця,Севастополь,Різні товари та послуги,Місячна,Відсоток,Одиниці,Один,NaN,1. З 2001 року. 2. За 2014-2021 роки дані наве...,Виключні події та обставини.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,100.4,100.5,100.3,101.7,100.2,100.5,101.4,100.5,100.4,102.0,103.5,NaN,104.6,103.6,101.1,105.7,100.5,103.2,101.8,102.0,100.2,102.6,99.7,99.6,NaN,103.3,102.8,103.5,101.8,101.3,102.2,99.5,100.5,100.1,101.7,100.8,100.9,NaN,100.5,100.4,100.5,100.2,100.4,101.1,102.0,99.9,100.4,100.8,101.3,100.9,NaN,100.9,100.5,101.1,100.7,100.2,101.0,101.0,100.4,100.5,102.3,100.1,100.0,NaN,100.5,100.1,99.9,100.2,100.2,100.0,99.8,99.9,100.6,100.7,100.6,100.1,NaN,100.6,100.7,99.9,99.4,99.3,100.3,99.5,100.2,100.4,100.3,99.9,99.5,NaN,99.9,100.3,100.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2441,Індекс споживчих цін,Рік до попереднього року,Україна,Індекс споживчих цін,Річна,Відсоток,Одиниці,Один,NaN,1. З 1993 року. 2. За 2014 рік дані наведено б...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,148.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2442,Індекс споживчих цін,Рік до попереднього року,Україна,Охорона здоров’я,Річна,Відсоток,Одиниці,Один,NaN,1. З 2002 року. 2. За 2014 рік дані наведено б...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2443,Індекс споживчих цін,Рік до попереднього року,Україна,"Предмети домашнього вжитку, побутова техніка т...",Річна,Відсоток,Одиниці,Один,NaN,1. З 2002 року. 2. За 2014 рік дані наведено б...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,145.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2444,Індекс споживчих цін,Рік до попереднього року,Україна,"Житло, вода, електроенергія, газ та інші види ...",Річна,Відсоток,Одиниці,Один,NaN,1. З 2002 року. 2. За 2014 рік дані наведено б...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,142.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,215.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,123.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2445,Індекс споживчих цін,Рік до попереднього року,Україна,Одяг і взуття,Річна,Відсоток,Одиниці,Один,NaN,1. З 2002 року. 2. За 2014 рік дані наведено б...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,133.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Фільтрація за територією та показником.** Залишаємо рядки з умовами: 1) `Територіальний розріз == 'Україна'` (без областей); 2) `Показник == 'Середні споживчі ціни на товари (послуги)'` (без індексів). Використовуємо `.copy()` щоб уникнути попереджень при зміні DataFrame.

In [32]:
df = df[
    (df['Територіальний розріз'] == 'Україна') &
    (df['Показник'] == 'Середні споживчі ціни на товари (послуги)')
].copy()

df

                                     Показник    Базисний період  \
0   Середні споживчі ціни на товари (послуги)  Не застосовується
1   Середні споживчі ціни на товари (послуги)  Не застосовується
2   Середні споживчі ціни на товари (послуги)  Не застосовується
3   Середні споживчі ціни на товари (послуги)  Не застосовується
4   Середні споживчі ціни на товари (послуги)  Не застосовується
5   Середні споживчі ціни на товари (послуги)  Не застосовується
7   Середні споживчі ціни на товари (послуги)  Не застосовується
9   Середні споживчі ціни на товари (послуги)  Не застосовується
12  Середні споживчі ціни на товари (послуги)  Не застосовується
13  Середні споживчі ціни на товари (послуги)  Не застосовується
14  Середні споживчі ціни на товари (послуги)  Не застосовується
15  Середні споживчі ціни на товари (послуги)  Не застосовується
16  Середні споживчі ціни на товари (послуги)  Не застосовується
17  Середні споживчі ціни на товари (послуги)  Не застосовується
18  Середні споживчі ціни на товари (послуги)  Не застосовується
19  Середні споживчі ціни на товари (послуги)  Не застосовується
22  Середні споживчі ціни на товари (послуги)  Не застосовується
23  Середні споживчі ціни на товари (послуги)  Не застосовується
24  Середні споживчі ціни на товари (послуги)  Не застосовується
26  Середні споживчі ціни на товари (послуги)  Не застосовується
29  Середні споживчі ціни на товари (послуги)  Не застосовується
30  Середні споживчі ціни на товари (послуги)  Не застосовується
31  Середні споживчі ціни на товари (послуги)  Не застосовується
32  Середні споживчі ціни на товари (послуги)  Не застосовується
33  Середні споживчі ціни на товари (послуги)  Не застосовується
34  Середні споживчі ціни на товари (послуги)  Не застосовується
35  Середні споживчі ціни на товари (послуги)  Не застосовується
36  Середні споживчі ціни на товари (послуги)  Не застосовується
37  Середні споживчі ціни на товари (послуги)  Не застосовується
38  Середні споживчі ціни на товари (послуги)  Не застосовується
39  Середні споживчі ціни на товари (послуги)  Не застосовується
40  Середні споживчі ціни на товари (послуги)  Не застосовується
42  Середні споживчі ціни на товари (послуги)  Не застосовується
43  Середні споживчі ціни на товари (послуги)  Не застосовується
44  Середні споживчі ціни на товари (послуги)  Не застосовується
45  Середні споживчі ціни на товари (послуги)  Не застосовується
46  Середні споживчі ціни на товари (послуги)  Не застосовується
47  Середні споживчі ціни на товари (послуги)  Не застосовується
49  Середні споживчі ціни на товари (послуги)  Не застосовується
50  Середні споживчі ціни на товари (послуги)  Не застосовується
51  Середні споживчі ціни на товари (послуги)  Не застосовується
52  Середні споживчі ціни на товари (послуги)  Не застосовується
53  Середні споживчі ціни на товари (послуги)  Не застосовується
55  Середні споживчі ціни на товари (послуги)  Не застосовується
56  Середні споживчі ціни на товари (послуги)  Не застосовується
58  Середні споживчі ціни на товари (послуги)  Не застосовується
64  Середні споживчі ціни на товари (послуги)  Не застосовується
66  Середні споживчі ціни на товари (послуги)  Не застосовується
68  Середні споживчі ціни на товари (послуги)  Не застосовується
69  Середні споживчі ціни на товари (послуги)  Не застосовується
71  Середні споживчі ціни на товари (послуги)  Не застосовується
72  Середні споживчі ціни на товари (послуги)  Не застосовується
73  Середні споживчі ціни на товари (послуги)  Не застосовується
74  Середні споживчі ціни на товари (послуги)  Не застосовується
75  Середні споживчі ціни на товари (послуги)  Не застосовується

   Територіальний розріз                               Тип товарів і послуг  \
0                Україна                               Птиця (тушки курячі)
1                Україна                               Сигарети без фільтру
2                Україна      Молоко пастеризоване жирністю до 2,6% включно
3                Україна                Судинорозширювальні засоби імпортні
4                Україна                   Сигарети з фільтром медіум класу
5                Україна                                           Картопля
7                Україна           Хліб пшеничний з борошна першого ґатунку
9                Україна                     Газ скраплений для автомобілів
12               Україна                             Стоматологічні послуги
13               Україна                                        Бензин А-92
14               Україна                                   Борошно пшеничне
15               Україна                                          Яловичина
16               Україна           Макаронні вироби з м’яких сортів пшениці
17               Україна  Жарознижувальні та знеболювальні препарати імп...
18               Україна                    Сметана жирністю до 15% включно
19               Україна                       Проїзд у міському транспорті
22               Україна                                               Сало
23               Україна                             Пиво вітчизняних марок
24               Україна                                Капуста білокачанна
26               Україна             Молочні суміші для дитячого харчування
29               Україна                                         Крупи ячні
30               Україна                                     Крупи пшеничні
31               Україна                                             Яблука
32               Україна  Послуги у сфері страхування особистого транспорту
33               Україна                                               Яйця
34               Україна                                                Рис
35               Україна                            Вина столові вітчизняні
36               Україна                                     Масло вершкове
37               Україна                             Антибіотики вітчизняні
38               Україна                                              Буряк
39               Україна                                        Філе куряче
40               Україна                                   Олія соняшникова
42               Україна                  Сигарети з фільтром преміум класу
43               Україна              Сигарети з фільтром вітчизняних марок
44               Україна              Судинорозширювальні засоби вітчизняні
45               Україна                                   Дошкільна освіта
46               Україна                                    Дизельне пальне
47               Україна            Хліб пшеничний з борошна вищого ґатунку
49               Україна                                      Крупи гречані
50               Україна                      Хліб житній, житньо-пшеничний
51               Україна                                        Бензин А-95
52               Україна                     Ковбаси варені першого ґатунку
53               Україна                                              Батон
55               Україна                                        Крупи манні
56               Україна  Жарознижувальні та знеболювальні препарати віт...
58               Україна                                            Горілка
64               Україна                                              Цукор
66               Україна                                              Пшоно
68               Україна               Плата за оренду 1-кімнатної квартири
69               Україна                                   Сири м’які жирні
71               Україна                               Антибіотики імпортні
72               Україна                                            Свинина
73               Україна                                             Морква
74               Україна                                    Цибуля ріпчаста
75               Україна                                      Риба морожена

   Періодичність              Одиниця виміру Масштабування  \
0        Місячна                    Кілограм       Одиниці
1        Місячна               Пачка (20 шт)       Одиниці
2        Місячна                      1000 г       Одиниці
3        Місячна            10 табл., капсул       Одиниці
4        Місячна               Пачка (20 шт)       Одиниці
5        Місячна                    Кілограм       Одиниці
7        Місячна                    Кілограм       Одиниці
9        Місячна                        Літр       Одиниці
12       Місячна                     Одиниця       Одиниці
13       Місячна                        Літр       Одиниці
14       Місячна                    Кілограм       Одиниці
15       Місячна                    Кілограм       Одиниці
16       Місячна                    Кілограм       Одиниці
17       Місячна                   1 пакетик       Одиниці
18       Місячна                    Кілограм       Одиниці
19       Місячна                      Квиток       Одиниці
22       Місячна                    Кілограм       Одиниці
23       Місячна                       0,5 л       Одиниці
24       Місячна                    Кілограм       Одиниці
26       Місячна                       250 г       Одиниці
29       Місячна                    Кілограм       Одиниці
30       Місячна                    Кілограм       Одиниці
31       Місячна                    Кілограм       Одиниці
32       Місячна  Вартість страхового полісу       Одиниці
33       Місячна                     Десяток       Одиниці
34       Місячна                    Кілограм       Одиниці
35       Місячна                      0,75 л       Одиниці
36       Місячна                       200 г       Одиниці
37       Місячна            10 табл., капсул       Одиниці
38       Місячна                    Кілограм       Одиниці
39       Місячна                    Кілограм       Одиниці
40       Місячна                        Літр       Одиниці
42       Місячна               Пачка (20 шт)       Одиниці
43       Місячна               Пачка (20 шт)       Одиниці
44       Місячна            10 табл., капсул       Одиниці
45       Місячна                        День       Одиниці
46       Місячна                        Літр       Одиниці
47       Місячна                    Кілограм       Одиниці
49       Місячна                    Кілограм       Одиниці
50       Місячна                    Кілограм       Одиниці
51       Місячна                        Літр       Одиниці
52       Місячна                    Кілограм       Одиниці
53       Місячна                       500 г       Одиниці
55       Місячна                    Кілограм       Одиниці
56       Місячна                    10 табл.       Одиниці
58       Місячна                       0,5 л       Одиниці
64       Місячна                    Кілограм       Одиниці
66       Місячна                    Кілограм       Одиниці
68       Місячна                      Місяць       Одиниці
69       Місячна                    Кілограм       Одиниці
71       Місячна            10 табл., капсул       Одиниці
72       Місячна                    Кілограм       Одиниці
73       Місячна                    Кілограм       Одиниці
74       Місячна                    Кілограм       Одиниці
75       Місячна                    Кілограм       Одиниці

   Кількість десяткових знаків Спеціальне значення даних  \
0                          Два                       NaN
1                          Два              Явищ не було
2                          Два                       NaN
3                          Два                       NaN
4                          Два                       NaN
5                          Два                       NaN
7                          Два                       NaN
9                          Два                       NaN
12                         Два                       NaN
13                         Два                       NaN
14                         Два                       NaN
15                         Два                       NaN
16                         Два                       NaN
17                         Два                       NaN
18                         Два                       NaN
19                         Два                       NaN
22                         Два                       NaN
23                         Два                       NaN
24                         Два                       NaN
26                         Два                       NaN
29                         Два                       NaN
30                         Два              Явищ не було
31                         Два                       NaN
32                         Два                       NaN
33                         Два                       NaN
34                         Два                       NaN
35                         Два                       NaN
36                         Два                       NaN
37                         Два                       NaN
38                         Два                       NaN
39                         Два                       NaN
40                         Два                       NaN
42                         Два                       NaN
43                         Два                       NaN
44                         Два                       NaN
45                         Два                       NaN
46                         Два                       NaN
47                         Два                       NaN
49                         Два                       NaN
50                         Два                       NaN
51                         Два                       NaN
52                         Два                       NaN
53                         Два                       NaN
55                         Два                       NaN
56                         Два                       NaN
58                         Два                       NaN
64                         Два                       NaN
66                         Два                       NaN
68                         Два                       NaN
69                         Два                       NaN
71                         Два                       NaN
72                         Два                       NaN
73                         Два                       NaN
74                         Два                       NaN
75                         Два                       NaN

                               Примітки часового ряду Примітки спостереження  \
0   1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
1   1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
2   1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
3   1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
4   1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
5   1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
7   1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
9   1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
12  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
13  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
14  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
15  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
16  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
17  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
18  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
19  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
22  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
23  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
24  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
26  1. З 2017 року. 2. Дані за одиницю вимірювання...    Відомості відсутні.
29  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
30  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
31  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
32  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
33  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
34  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
35  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
36  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
37  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
38  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
39  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
40  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
42  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
43  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
44  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
45  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
46  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
47  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
49  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
50  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
51  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
52  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
53  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
55  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
56  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
58  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
64  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
66  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
68  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
69  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
71  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
72  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
73  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
74  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN
75  1. З 2017 року. 2. Дані за одиницю вимірювання...                    NaN

    1991  1991-M01  1991-M02  1991-M03  1991-M04  1991-M05  1991-M06  \
0    NaN       NaN       NaN       NaN       NaN       NaN       NaN
1    NaN       NaN       NaN       NaN       NaN       NaN       NaN
2    NaN       NaN       NaN       NaN       NaN       NaN       NaN
3    NaN       NaN       NaN       NaN       NaN       NaN       NaN
4    NaN       NaN       NaN       NaN       NaN       NaN       NaN
5    NaN       NaN       NaN       NaN       NaN       NaN       NaN
7    NaN       NaN       NaN       NaN       NaN       NaN       NaN
9    NaN       NaN       NaN       NaN       NaN       NaN       NaN
12   NaN       NaN       NaN       NaN       NaN       NaN       NaN
13   NaN       NaN       NaN       NaN       NaN       NaN       NaN
14   NaN       NaN       NaN       NaN       NaN       NaN       NaN
15   NaN       NaN       NaN       NaN       NaN       NaN       NaN
16   NaN       NaN       NaN       NaN       NaN       NaN       NaN
17   NaN       NaN       NaN       NaN       NaN       NaN       NaN
18   NaN       NaN       NaN       NaN       NaN       NaN       NaN
19   NaN       NaN       NaN       NaN       NaN       NaN       NaN
22   NaN       NaN       NaN       NaN       NaN       NaN       NaN

**Вибір товарів.** Залишаємо 8 позицій: хліб, молоко, картопля, курка, яловичина, бензин А-92, проїзд у міському транспорті, борошно. Це базові продукти та послуги, репрезентативні для споживчого кошика.

In [33]:
products = [
    'Хліб пшеничний з борошна першого ґатунку',
    'Молоко пастеризоване жирністю до 2,6% включно',
    'Картопля',
    'Птиця (тушки курячі)',
    'Яловичина',
    'Бензин А-92',
    'Проїзд у міському транспорті',
    'Борошно пшеничне'
]
df = df[df['Тип товарів і послуг'].isin(products)].copy()

df

,Показник,Базисний період,Територіальний розріз,Тип товарів і послуг,Періодичність,Одиниця виміру,Масштабування,Кількість десяткових знаків,Спеціальне значення даних,Примітки часового ряду,Примітки спостереження,1991,1991-M01,1991-M02,1991-M03,1991-M04,1991-M05,1991-M06,1991-M07,1991-M08,1991-M09,1991-M10,1991-M11,1991-M12,1992,1992-M01,1992-M02,1992-M03,1992-M04,1992-M05,1992-M06,1992-M07,1992-M08,1992-M09,1992-M10,1992-M11,1992-M12,1993,1993-M01,1993-M02,1993-M03,1993-M04,1993-M05,1993-M06,1993-M07,1993-M08,1993-M09,1993-M10,1993-M11,1993-M12,1994,1994-M01,1994-M02,1994-M03,1994-M04,1994-M05,1994-M06,1994-M07,1994-M08,1994-M09,1994-M10,1994-M11,1994-M12,1995,1995-M01,1995-M02,1995-M03,1995-M04,1995-M05,1995-M06,1995-M07,1995-M08,1995-M09,1995-M10,1995-M11,1995-M12,1996,1996-M01,1996-M02,1996-M03,1996-M04,1996-M05,1996-M06,1996-M07,1996-M08,1996-M09,1996-M10,1996-M11,1996-M12,1997,1997-M01,1997-M02,1997-M03,1997-M04,1997-M05,1997-M06,1997-M07,1997-M08,1997-M09,1997-M10,1997-M11,1997-M12,1998,1998-M01,1998-M02,1998-M03,1998-M04,1998-M05,1998-M06,1998-M07,1998-M08,1998-M09,1998-M10,1998-M11,1998-M12,1999,1999-M01,1999-M02,1999-M03,1999-M04,1999-M05,1999-M06,1999-M07,1999-M08,1999-M09,1999-M10,1999-M11,1999-M12,2000,2000-M01,2000-M02,2000-M03,2000-M04,2000-M05,2000-M06,2000-M07,2000-M08,2000-M09,2000-M10,2000-M11,2000-M12,2001,2001-M01,2001-M02,2001-M03,2001-M04,2001-M05,2001-M06,2001-M07,2001-M08,2001-M09,2001-M10,2001-M11,2001-M12,2002,2002-M01,2002-M02,2002-M03,2002-M04,2002-M05,2002-M06,2002-M07,2002-M08,2002-M09,2002-M10,2002-M11,2002-M12,2003,2003-M01,2003-M02,2003-M03,2003-M04,2003-M05,2003-M06,2003-M07,2003-M08,2003-M09,2003-M10,2003-M11,2003-M12,2004,2004-M01,2004-M02,2004-M03,2004-M04,2004-M05,2004-M06,2004-M07,2004-M08,2004-M09,2004-M10,2004-M11,2004-M12,2005,2005-M01,2005-M02,2005-M03,2005-M04,2005-M05,2005-M06,2005-M07,2005-M08,2005-M09,2005-M10,2005-M11,2005-M12,2006,2006-M01,2006-M02,2006-M03,2006-M04,2006-M05,2006-M06,2006-M07,2006-M08,2006-M09,2006-M10,2006-M11,2006-M12,2007,2007-M01,2007-M02,2007-M03,2007-M04,2007-M05,2007-M06,2007-M07,2007-M08,2007-M09,2007-M10,2007-M11,2007-M12,2008,2008-M01,2008-M02,2008-M03,2008-M04,2008-M05,2008-M06,2008-M07,2008-M08,2008-M09,2008-M10,2008-M11,2008-M12,2009,2009-M01,2009-M02,2009-M03,2009-M04,2009-M05,2009-M06,2009-M07,2009-M08,2009-M09,2009-M10,2009-M11,2009-M12,2010,2010-M01,2010-M02,2010-M03,2010-M04,2010-M05,2010-M06,2010-M07,2010-M08,2010-M09,2010-M10,2010-M11,2010-M12,2011,2011-M01,2011-M02,2011-M03,2011-M04,2011-M05,2011-M06,2011-M07,2011-M08,2011-M09,2011-M10,2011-M11,2011-M12,2012,2012-M01,2012-M02,2012-M03,2012-M04,2012-M05,2012-M06,2012-M07,2012-M08,2012-M09,2012-M10,2012-M11,2012-M12,2013,2013-M01,2013-M02,2013-M03,2013-M04,2013-M05,2013-M06,2013-M07,2013-M08,2013-M09,2013-M10,2013-M11,2013-M12,2014,2014-M01,2014-M02,2014-M03,2014-M04,2014-M05,2014-M06,2014-M07,2014-M08,2014-M09,2014-M10,2014-M11,2014-M12,2015,2015-M01,2015-M02,2015-M03,2015-M04,2015-M05,2015-M06,2015-M07,2015-M08,2015-M09,2015-M10,2015-M11,2015-M12,2016,2016-M01,2016-M02,2016-M03,2016-M04,2016-M05,2016-M06,2016-M07,2016-M08,2016-M09,2016-M10,2016-M11,2016-M12,2017,2017-M01,2017-M02,2017-M03,2017-M04,2017-M05,2017-M06,2017-M07,2017-M08,2017-M09,2017-M10,2017-M11,2017-M12,2018,2018-M01,2018-M02,2018-M03,2018-M04,2018-M05,2018-M06,2018-M07,2018-M08,2018-M09,2018-M10,2018-M11,2018-M12,2019,2019-M01,2019-M02,2019-M03,2019-M04,2019-M05,2019-M06,2019-M07,2019-M08,2019-M09,2019-M10,2019-M11,2019-M12,2020,2020-M01,2020-M02,2020-M03,2020-M04,2020-M05,2020-M06,2020-M07,2020-M08,2020-M09,2020-M10,2020-M11,2020-M12,2021,2021-M01,2021-M02,2021-M03,2021-M04,2021-M05,2021-M06,2021-M07,2021-M08,2021-M09,2021-M10,2021-M11,2021-M12,2022,2022-M01,2022-M02,2022-M03,2022-M04,2022-M05,2022-M06,2022-M07,2022-M08,2022-M09,2022-M10,2022-M11,2022-M12,2023,2023-M01,2023-M02,2023-M03,2023-M04,2023-M05,2023-M06,2023-M07,2023-M08,2023-M09,2023-M10,2023-M11,2023-M12,2024,2024-M01,2024-M02,2024-M03,2024-M04,2024-M05,2024-M06,2024-M07,2024-M08,2024-M09,2024-M10,2024-M11,2024-M12,2025,2025-M01,2025-M02,2025-M03,2025-M04,2025-M05,2025-M06,2025-M07,2025-M08,2025-M09,2025-M10,2025-M11,2025-M12,2026-M01
0,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Птиця (тушки курячі),Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.12,42.70,42.95,43.83,44.45,45.35,49.85,53.94,55.50,55.26,53.95,53.90,NaN,54.86,53.72,54.08,55.17,54.81,54.78,54.90,55.69,58.62,58.64,58.32,57.83,NaN,58.66,58.15,58.32,58.40,59.37,60.22,61.78,62.22,62.27,62.07,60.74,59.37,NaN,58.23,55.09,54.12,52.22,49.59,50.50,51.25,52.18,52.93,54.38,55.17,55.96,NaN,57.40,60.13,63.06,65.35,67.25,68.19,69.34,69.94,71.40,72.42,71.02,70.82,NaN,73.52,74.12,76.19,76.04,74.81,79.54,80.83,82.43,82.43,82.96,80.49,81.29,NaN,82.45,84.63,86.71,87.67,87.56,88.69,90.37,91.43,91.50,91.67,91.27,90.25,NaN,89.92,88.31,87.89,88.03,89.28,87.35,86.76,86.79,90.95,92.22,92.38,92.55,NaN,91.45,91.85,94.95,98.15,107.22,113.94,115.55,117.95,118.03,119.98,117.93,116.20,112.47
2,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,"Молоко пастеризоване жирністю до 2,6% включно",Місячна,1000 г,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.93,18.58,19.04,19.26,19.35,19.29,19.40,19.61,19.95,20.70,21.27,21.77,NaN,22.01,21.95,22.13,22.03,22.13,22.02,21.90,21.99,22.36,22.85,23.39,23.73,NaN,23.87,24.13,24.18,24.32,24.25,24.15,24.23,24.43,24.73,25.14,25.22,25.31,NaN,24.91,24.99,25.00,25.01,25.09,24.95,24.91,24.83,25.00,25.19,25.39,25.60,NaN,25.41,25.83,25.96,25.99,26.44,26.42,26.50,26.62,27.20,27.63,27.96,28.55,NaN,28.93,29.37,30.53,31.46,31.92,32.29,32.61,32.40,32.90,33.27,33.86,34.28,NaN,35.24,35.42,35.90,35.69,35.66,35.78,36.10,36.33,36.23,36.63,37.09,37.69,NaN,38.15,38.70,38.98,39.41,38.65,38.73,39.01,39.40,40.13,41.62,43.71,45.64,NaN,45.89,46.25,47.15,47.71,47.39,47.18,47.10,47.72,47.45,49.20,49.05,49.56,49.95
5,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Картопля,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.58,6.11,6.25,6.71,8.36,11.12,8.99,7.44,6.76,6.19,5.95,6.00,NaN,6.43,6.89,7.58,7.83,7.54,8.73,7.95,7.56,6.86,6.52,6.76,7.99,NaN,9.33,10.09,10.16,10.73,14.07,17.26,15.30,15.02,14.63,15.29,14.14,13.52,NaN,13.13,12.80,12.89,14.75,15.27,16.06,12.67,10.02,9.08,8.96,9.23,10.15,NaN,11.14,11.87,12.17,11.92,11.96,13.30,11.79,8.66,8.32,8.69,8.61,8.76,NaN,9.29,9.54,11.70,10.23,9.64,12.24,18.93,13.56,10.84,9.91,9.13,9.20,NaN,9.40,9.57,9.55,9.49,9.89,12.04,20.25,12.87,10.95,10.16,11.90,15.13,NaN,21.46,22.75,22.73,22.45,24.53,28.39,20.08,19.73,20.67,25.85,29.79,29.74,NaN,30.09,29.87,30.12,30.63,31.95,34.73,24.89,21.24,17.93,16.85,15.79,14.76,15.51
7,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Хліб пшеничний з борошна першого ґатунку,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.99,12.41,12.67,12.78,12.87,13.00,13.11,13.28,13.50,13.72,13.98,14.19,NaN,14.41,14.68,14.90,15.14,15.27,15.35,15.49,15.68,16.14,16.54,17.22,17.48,NaN,17.78,18.01,18.22,18.41,18.68,18.99,19.08,19.15,19.24,19.31,19.55,19.58,NaN,19.74,19.78,19.81,19.86,19.98,20.09,20.12,20.16,20.37,20.62,20.99,21.40,NaN,21.98,22.52,23.19,23.50,23.76,23.80,23.86,23.91,24.48,25.18,25.78,26.29,NaN,27.11,28.29,29.50,29.77,30.64,31.65,32.10,32.00,32.20,32.76,32.63,33.23,NaN,34.20,34.64,34.67,34.81,34.72,34.65,34.88,35.11,35.16,35.47,35.77,36.02,NaN,35.72,35.94,36.38,36.64,36.76,37.09,38.35,39.59,40.03,40.81,41.29,42.52,NaN,43.42,43.69,44.25,45.06,45.38,46.19,46.31,46.39,47.07,47.68,48.26,48.81,49.88
13,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Бензин А-92,Місячна,Літр,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.19,23.73,23.75,24.05,24.24,24.04,23.81,23.83,24.35,25.68,26.61,27.30,NaN,28.58,29.20,28.50,28.28,28.34,28.39,28.24,28.49,30.09,31.79,31.12,29.31,NaN,27.58,27.29,27.23,27.75,28.93,28.87,27.96,27.65,27.58,27.55,27.49,26.98,NaN,25.78,25.41,25.12,22.84,20.85,20.79,21.49,22.11,22.24,22.41,23.12,23.82,NaN,24.52,26.07,27.54,27.73,28.16,28.36,29.18,29.32,29.15,29.97,30.80,29.63,NaN,30.52,33.19,35.45,34.11,40.87,50.38,49.06,48.44,47.88,47.65,48.23,49.96,NaN,49.10,46.95,45.74,44.42,43.16,41.95,45.31,49.01,51.70,53.35,52.80,49.65,NaN,47.51,47.56,48.97,51.08,51.96,52.65,53.14,53.03,53.34,53.30,52.84,52.60,NaN,53.34,53.52,53.06,52.29,51.63,53.48,56.35,56.16,55.70,55.90,55.70,55.91,56.69
14,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Борошно пшеничне,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.53,8.68,8.94,9.08,9.15,9.16,9.17,9.12,9.19,9.21,9.32,9.44,NaN,9.55,9.65,9.74,9.79,9.88,9.99,10.04,10.23,10.74,11.10,11.24,11.34,NaN,11.36,11.50,11.64,11.71,11.82,11.83,11.84,11.74,11.65,11.47,11.28,11.22,NaN,11.10,11.18,11.34,11.60,11.75,11.79,11.67,11.57,11.43,11.61,12.31,12.70,NaN,13.18,13.75,14.14,14.49,14.38,14.33,14.25,14.30,14.38,14.48,14.66,15.01,NaN,15.48,15.65,16.81,18.04,18.34,18.29,17.89,17.41,17.23,16.94,16.73,16.79,NaN,16.85,16.71,16.68,16.62,16.55,16.40,16.29,15.89,16.03,15.89,15.81,15.85,NaN,15.69,15.79,15.68,15.52,15.56,15.95,16.52,17.21,18.15,18.66,19.21,19.93,NaN,20.43,20.73,21.34,21.36,21.71,21.71,21.75,21.74,21.82,21.95,21.95,21.89,22.04
15,Середні споживчі ціни на товари (послуги),Не застосовується,Україна,Яловичина,Місячна,Кілограм,Одиниці,Два,NaN,1. З 2017 року. 2. Дані за одиницю вимірювання...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.46,93.68,95.69,97.49,99.28,102.70,105.43,106.84,110.10,112.12,112.53,114.30,NaN,117.14,120.39,122.16,124.70,124.48,124.41,124.51,124.99,126.00,126.93,127.43,128.12,NaN,129.06,128.36,127.56,128.50,128.71,128.50,129.37,130.24,131.12,132.20,132.05,132.81,NaN,134.85,136.69,138.07,141.06,141.73,142.65,142.44,142.59,143.27,143.29,144.16,144.82,NaN,149.51,153.99,157.24,159.13,160.30,160.94,162.45,165.00,172.04,175.51,179.37,182.84,NaN,195.61,208.02,221.45,216.39,211.23,205.59,200.63,200.20,200.92,203.45,200.65,203.18,NaN,204.95,203.61,206.36,210.95,214.60,219.04,223.52,227.99,230.59,233.76,238.05,243.64,NaN,251.64,260.15,263.97,266.10,268.23,269.24,270.01,270.56,273.80,279.76,284.53,288.73,NaN,293.27,297.92,303.16,307.16,314.73,323.18,329.33,332.53,343.79,348.55,349.24,352.21,356.73

**Вибір часового періоду.** Регулярний вираз `^\d{4}-M\d{2}$` вибирає колонки формату YYYY-M01, YYYY-M02 тощо. Фільтр за роком обмежує період 2017–2025. Річні стовпці (1991, 1992, …) виключаються.

In [34]:
month_cols = [c for c in df.columns if re.match(r'^\d{4}-M\d{2}$', str(c))]
month_cols = [c for c in month_cols if 2017 <= int(c[:4]) <= 2025]

df[month_cols]

,2017-M01,2017-M02,2017-M03,2017-M04,2017-M05,2017-M06,2017-M07,2017-M08,2017-M09,2017-M10,2017-M11,2017-M12,2018-M01,2018-M02,2018-M03,2018-M04,2018-M05,2018-M06,2018-M07,2018-M08,2018-M09,2018-M10,2018-M11,2018-M12,2019-M01,2019-M02,2019-M03,2019-M04,2019-M05,2019-M06,2019-M07,2019-M08,2019-M09,2019-M10,2019-M11,2019-M12,2020-M01,2020-M02,2020-M03,2020-M04,2020-M05,2020-M06,2020-M07,2020-M08,2020-M09,2020-M10,2020-M11,2020-M12,2021-M01,2021-M02,2021-M03,2021-M04,2021-M05,2021-M06,2021-M07,2021-M08,2021-M09,2021-M10,2021-M11,2021-M12,2022-M01,2022-M02,2022-M03,2022-M04,2022-M05,2022-M06,2022-M07,2022-M08,2022-M09,2022-M10,2022-M11,2022-M12,2023-M01,2023-M02,2023-M03,2023-M04,2023-M05,2023-M06,2023-M07,2023-M08,2023-M09,2023-M10,2023-M11,2023-M12,2024-M01,2024-M02,2024-M03,2024-M04,2024-M05,2024-M06,2024-M07,2024-M08,2024-M09,2024-M10,2024-M11,2024-M12,2025-M01,2025-M02,2025-M03,2025-M04,2025-M05,2025-M06,2025-M07,2025-M08,2025-M09,2025-M10,2025-M11,2025-M12
0,42.12,42.70,42.95,43.83,44.45,45.35,49.85,53.94,55.50,55.26,53.95,53.90,54.86,53.72,54.08,55.17,54.81,54.78,54.90,55.69,58.62,58.64,58.32,57.83,58.66,58.15,58.32,58.40,59.37,60.22,61.78,62.22,62.27,62.07,60.74,59.37,58.23,55.09,54.12,52.22,49.59,50.50,51.25,52.18,52.93,54.38,55.17,55.96,57.40,60.13,63.06,65.35,67.25,68.19,69.34,69.94,71.40,72.42,71.02,70.82,73.52,74.12,76.19,76.04,74.81,79.54,80.83,82.43,82.43,82.96,80.49,81.29,82.45,84.63,86.71,87.67,87.56,88.69,90.37,91.43,91.50,91.67,91.27,90.25,89.92,88.31,87.89,88.03,89.28,87.35,86.76,86.79,90.95,92.22,92.38,92.55,91.45,91.85,94.95,98.15,107.22,113.94,115.55,117.95,118.03,119.98,117.93,116.20
2,17.93,18.58,19.04,19.26,19.35,19.29,19.40,19.61,19.95,20.70,21.27,21.77,22.01,21.95,22.13,22.03,22.13,22.02,21.90,21.99,22.36,22.85,23.39,23.73,23.87,24.13,24.18,24.32,24.25,24.15,24.23,24.43,24.73,25.14,25.22,25.31,24.91,24.99,25.00,25.01,25.09,24.95,24.91,24.83,25.00,25.19,25.39,25.60,25.41,25.83,25.96,25.99,26.44,26.42,26.50,26.62,27.20,27.63,27.96,28.55,28.93,29.37,30.53,31.46,31.92,32.29,32.61,32.40,32.90,33.27,33.86,34.28,35.24,35.42,35.90,35.69,35.66,35.78,36.10,36.33,36.23,36.63,37.09,37.69,38.15,38.70,38.98,39.41,38.65,38.73,39.01,39.40,40.13,41.62,43.71,45.64,45.89,46.25,47.15,47.71,47.39,47.18,47.10,47.72,47.45,49.20,49.05,49.56
5,5.58,6.11,6.25,6.71,8.36,11.12,8.99,7.44,6.76,6.19,5.95,6.00,6.43,6.89,7.58,7.83,7.54,8.73,7.95,7.56,6.86,6.52,6.76,7.99,9.33,10.09,10.16,10.73,14.07,17.26,15.30,15.02,14.63,15.29,14.14,13.52,13.13,12.80,12.89,14.75,15.27,16.06,12.67,10.02,9.08,8.96,9.23,10.15,11.14,11.87,12.17,11.92,11.96,13.30,11.79,8.66,8.32,8.69,8.61,8.76,9.29,9.54,11.70,10.23,9.64,12.24,18.93,13.56,10.84,9.91,9.13,9.20,9.40,9.57,9.55,9.49,9.89,12.04,20.25,12.87,10.95,10.16,11.90,15.13,21.46,22.75,22.73,22.45,24.53,28.39,20.08,19.73,20.67,25.85,29.79,29.74,30.09,29.87,30.12,30.63,31.95,34.73,24.89,21.24,17.93,16.85,15.79,14.76
7,11.99,12.41,12.67,12.78,12.87,13.00,13.11,13.28,13.50,13.72,13.98,14.19,14.41,14.68,14.90,15.14,15.27,15.35,15.49,15.68,16.14,16.54,17.22,17.48,17.78,18.01,18.22,18.41,18.68,18.99,19.08,19.15,19.24,19.31,19.55,19.58,19.74,19.78,19.81,19.86,19.98,20.09,20.12,20.16,20.37,20.62,20.99,21.40,21.98,22.52,23.19,23.50,23.76,23.80,23.86,23.91,24.48,25.18,25.78,26.29,27.11,28.29,29.50,29.77,30.64,31.65,32.10,32.00,32.20,32.76,32.63,33.23,34.20,34.64,34.67,34.81,34.72,34.65,34.88,35.11,35.16,35.47,35.77,36.02,35.72,35.94,36.38,36.64,36.76,37.09,38.35,39.59,40.03,40.81,41.29,42.52,43.42,43.69,44.25,45.06,45.38,46.19,46.31,46.39,47.07,47.68,48.26,48.81
13,23.19,23.73,23.75,24.05,24.24,24.04,23.81,23.83,24.35,25.68,26.61,27.30,28.58,29.20,28.50,28.28,28.34,28.39,28.24,28.49,30.09,31.79,31.12,29.31,27.58,27.29,27.23,27.75,28.93,28.87,27.96,27.65,27.58,27.55,27.49,26.98,25.78,25.41,25.12,22.84,20.85,20.79,21.49,22.11,22.24,22.41,23.12,23.82,24.52,26.07,27.54,27.73,28.16,28.36,29.18,29.32,29.15,29.97,30.80,29.63,30.52,33.19,35.45,34.11,40.87,50.38,49.06,48.44,47.88,47.65,48.23,49.96,49.10,46.95,45.74,44.42,43.16,41.95,45.31,49.01,51.70,53.35,52.80,49.65,47.51,47.56,48.97,51.08,51.96,52.65,53.14,53.03,53.34,53.30,52.84,52.60,53.34,53.52,53.06,52.29,51.63,53.48,56.35,56.16,55.70,55.90,55.70,55.91
14,8.53,8.68,8.94,9.08,9.15,9.16,9.17,9.12,9.19,9.21,9.32,9.44,9.55,9.65,9.74,9.79,9.88,9.99,10.04,10.23,10.74,11.10,11.24,11.34,11.36,11.50,11.64,11.71,11.82,11.83,11.84,11.74,11.65,11.47,11.28,11.22,11.10,11.18,11.34,11.60,11.75,11.79,11.67,11.57,11.43,11.61,12.31,12.70,13.18,13.75,14.14,14.49,14.38,14.33,14.25,14.30,14.38,14.48,14.66,15.01,15.48,15.65,16.81,18.04,18.34,18.29,17.89,17.41,17.23,16.94,16.73,16.79,16.85,16.71,16.68,16.62,16.55,16.40,16.29,15.89,16.03,15.89,15.81,15.85,15.69,15.79,15.68,15.52,15.56,15.95,16.52,17.21,18.15,18.66,19.21,19.93,20.43,20.73,21.34,21.36,21.71,21.71,21.75,21.74,21.82,21.95,21.95,21.89
15,89.46,93.68,95.69,97.49,99.28,102.70,105.43,106.84,110.10,112.12,112.53,114.30,117.14,120.39,122.16,124.70,124.48,124.41,124.51,124.99,126.00,126.93,127.43,128.12,129.06,128.36,127.56,128.50,128.71,128.50,129.37,130.24,131.12,132.20,132.05,132.81,134.85,136.69,138.07,141.06,141.73,142.65,142.44,142.59,143.27,143.29,144.16,144.82,149.51,153.99,157.24,159.13,160.30,160.94,162.45,165.00,172.04,175.51,179.37,182.84,195.61,208.02,221.45,216.39,211.23,205.59,200.63,200.20,200.92,203.45,200.65,203.18,204.95,203.61,206.36,210.95,214.60,219.04,223.52,227.99,230.59,233.76,238.05,243.64,251.64,260.15,263.97,266.10,268.23,269.24,270.01,270.56,273.80,279.76,284.53,288.73,293.27,297.92,303.16,307.16,314.73,323.18,329.33,332.53,343.79,348.55,349.24,352.21
19,2.46,2.51,2.62,2.77,2.79,2.82,2.88,2.96,3.03,3.06,3.11,3.12,3.17,3.22,3.23,3.40,3.47,3.50,3.75,4.03,4.10,4.10,4.24,4.44,4.47,4.67,4.82,4.88,4.91,4.97,5.00,5.02,5.04,5.06,5.10,5.11,5.31,5.37,5.39,5.39,5.39,5.41,5.41,5.51,5.51,5.51,5.51,5.51,5.57,5.58,5.61,5.68,5.80,6.21,6.46,6.87,6.91,7.07,7.27,7.32,7.33,7.53,7.60,7.44,7.54,7.77,8.11,8.44,8.48,8.57,8.64,8.57,8.58,8.58,8.58,8.58,8.57,8.57,8.59,8.63,8.69,8.69,8.69,8.98,9.09,9.09,9.16,9.31,9.31,9.35,9.49,9.62,9.73,9.73,9.73,10.26,10.58,10.59,11.09,11.18,11.50,11.84,11.87,11.87,11.92,11.94,11.94,11.94

**Скорочення колонок.** Залишаємо лише корисні колонки: метадані (тип товару, одиниця виміру) та місячні ціни. Видаляємо зайві стовпці (Показник, Примітки тощо). `reset_index(drop=True)` скидає індекси для зручності.

In [35]:
columns_to_keep = ['Тип товарів і послуг', 'Одиниця виміру'] + month_cols
df = df[columns_to_keep].reset_index(drop=True)

df

,Тип товарів і послуг,Одиниця виміру,2017-M01,2017-M02,2017-M03,2017-M04,2017-M05,2017-M06,2017-M07,2017-M08,2017-M09,2017-M10,2017-M11,2017-M12,2018-M01,2018-M02,2018-M03,2018-M04,2018-M05,2018-M06,2018-M07,2018-M08,2018-M09,2018-M10,2018-M11,2018-M12,2019-M01,2019-M02,2019-M03,2019-M04,2019-M05,2019-M06,2019-M07,2019-M08,2019-M09,2019-M10,2019-M11,2019-M12,2020-M01,2020-M02,2020-M03,2020-M04,2020-M05,2020-M06,2020-M07,2020-M08,2020-M09,2020-M10,2020-M11,2020-M12,2021-M01,2021-M02,2021-M03,2021-M04,2021-M05,2021-M06,2021-M07,2021-M08,2021-M09,2021-M10,2021-M11,2021-M12,2022-M01,2022-M02,2022-M03,2022-M04,2022-M05,2022-M06,2022-M07,2022-M08,2022-M09,2022-M10,2022-M11,2022-M12,2023-M01,2023-M02,2023-M03,2023-M04,2023-M05,2023-M06,2023-M07,2023-M08,2023-M09,2023-M10,2023-M11,2023-M12,2024-M01,2024-M02,2024-M03,2024-M04,2024-M05,2024-M06,2024-M07,2024-M08,2024-M09,2024-M10,2024-M11,2024-M12,2025-M01,2025-M02,2025-M03,2025-M04,2025-M05,2025-M06,2025-M07,2025-M08,2025-M09,2025-M10,2025-M11,2025-M12
0,Птиця (тушки курячі),Кілограм,42.12,42.70,42.95,43.83,44.45,45.35,49.85,53.94,55.50,55.26,53.95,53.90,54.86,53.72,54.08,55.17,54.81,54.78,54.90,55.69,58.62,58.64,58.32,57.83,58.66,58.15,58.32,58.40,59.37,60.22,61.78,62.22,62.27,62.07,60.74,59.37,58.23,55.09,54.12,52.22,49.59,50.50,51.25,52.18,52.93,54.38,55.17,55.96,57.40,60.13,63.06,65.35,67.25,68.19,69.34,69.94,71.40,72.42,71.02,70.82,73.52,74.12,76.19,76.04,74.81,79.54,80.83,82.43,82.43,82.96,80.49,81.29,82.45,84.63,86.71,87.67,87.56,88.69,90.37,91.43,91.50,91.67,91.27,90.25,89.92,88.31,87.89,88.03,89.28,87.35,86.76,86.79,90.95,92.22,92.38,92.55,91.45,91.85,94.95,98.15,107.22,113.94,115.55,117.95,118.03,119.98,117.93,116.20
1,"Молоко пастеризоване жирністю до 2,6% включно",1000 г,17.93,18.58,19.04,19.26,19.35,19.29,19.40,19.61,19.95,20.70,21.27,21.77,22.01,21.95,22.13,22.03,22.13,22.02,21.90,21.99,22.36,22.85,23.39,23.73,23.87,24.13,24.18,24.32,24.25,24.15,24.23,24.43,24.73,25.14,25.22,25.31,24.91,24.99,25.00,25.01,25.09,24.95,24.91,24.83,25.00,25.19,25.39,25.60,25.41,25.83,25.96,25.99,26.44,26.42,26.50,26.62,27.20,27.63,27.96,28.55,28.93,29.37,30.53,31.46,31.92,32.29,32.61,32.40,32.90,33.27,33.86,34.28,35.24,35.42,35.90,35.69,35.66,35.78,36.10,36.33,36.23,36.63,37.09,37.69,38.15,38.70,38.98,39.41,38.65,38.73,39.01,39.40,40.13,41.62,43.71,45.64,45.89,46.25,47.15,47.71,47.39,47.18,47.10,47.72,47.45,49.20,49.05,49.56
2,Картопля,Кілограм,5.58,6.11,6.25,6.71,8.36,11.12,8.99,7.44,6.76,6.19,5.95,6.00,6.43,6.89,7.58,7.83,7.54,8.73,7.95,7.56,6.86,6.52,6.76,7.99,9.33,10.09,10.16,10.73,14.07,17.26,15.30,15.02,14.63,15.29,14.14,13.52,13.13,12.80,12.89,14.75,15.27,16.06,12.67,10.02,9.08,8.96,9.23,10.15,11.14,11.87,12.17,11.92,11.96,13.30,11.79,8.66,8.32,8.69,8.61,8.76,9.29,9.54,11.70,10.23,9.64,12.24,18.93,13.56,10.84,9.91,9.13,9.20,9.40,9.57,9.55,9.49,9.89,12.04,20.25,12.87,10.95,10.16,11.90,15.13,21.46,22.75,22.73,22.45,24.53,28.39,20.08,19.73,20.67,25.85,29.79,29.74,30.09,29.87,30.12,30.63,31.95,34.73,24.89,21.24,17.93,16.85,15.79,14.76
3,Хліб пшеничний з борошна першого ґатунку,Кілограм,11.99,12.41,12.67,12.78,12.87,13.00,13.11,13.28,13.50,13.72,13.98,14.19,14.41,14.68,14.90,15.14,15.27,15.35,15.49,15.68,16.14,16.54,17.22,17.48,17.78,18.01,18.22,18.41,18.68,18.99,19.08,19.15,19.24,19.31,19.55,19.58,19.74,19.78,19.81,19.86,19.98,20.09,20.12,20.16,20.37,20.62,20.99,21.40,21.98,22.52,23.19,23.50,23.76,23.80,23.86,23.91,24.48,25.18,25.78,26.29,27.11,28.29,29.50,29.77,30.64,31.65,32.10,32.00,32.20,32.76,32.63,33.23,34.20,34.64,34.67,34.81,34.72,34.65,34.88,35.11,35.16,35.47,35.77,36.02,35.72,35.94,36.38,36.64,36.76,37.09,38.35,39.59,40.03,40.81,41.29,42.52,43.42,43.69,44.25,45.06,45.38,46.19,46.31,46.39,47.07,47.68,48.26,48.81
4,Бензин А-92,Літр,23.19,23.73,23.75,24.05,24.24,24.04,23.81,23.83,24.35,25.68,26.61,27.30,28.58,29.20,28.50,28.28,28.34,28.39,28.24,28.49,30.09,31.79,31.12,29.31,27.58,27.29,27.23,27.75,28.93,28.87,27.96,27.65,27.58,27.55,27.49,26.98,25.78,25.41,25.12,22.84,20.85,20.79,21.49,22.11,22.24,22.41,23.12,23.82,24.52,26.07,27.54,27.73,28.16,28.36,29.18,29.32,29.15,29.97,30.80,29.63,30.52,33.19,35.45,34.11,40.87,50.38,49.06,48.44,47.88,47.65,48.23,49.96,49.10,46.95,45.74,44.42,43.16,41.95,45.31,49.01,51.70,53.35,52.80,49.65,47.51,47.56,48.97,51.08,51.96,52.65,53.14,53.03,53.34,53.30,52.84,52.60,53.34,53.52,53.06,52.29,51.63,53.48,56.35,56.16,55.70,55.90,55.70,55.91
5,Борошно пшеничне,Кілограм,8.53,8.68,8.94,9.08,9.15,9.16,9.17,9.12,9.19,9.21,9.32,9.44,9.55,9.65,9.74,9.79,9.88,9.99,10.04,10.23,10.74,11.10,11.24,11.34,11.36,11.50,11.64,11.71,11.82,11.83,11.84,11.74,11.65,11.47,11.28,11.22,11.10,11.18,11.34,11.60,11.75,11.79,11.67,11.57,11.43,11.61,12.31,12.70,13.18,13.75,14.14,14.49,14.38,14.33,14.25,14.30,14.38,14.48,14.66,15.01,15.48,15.65,16.81,18.04,18.34,18.29,17.89,17.41,17.23,16.94,16.73,16.79,16.85,16.71,16.68,16.62,16.55,16.40,16.29,15.89,16.03,15.89,15.81,15.85,15.69,15.79,15.68,15.52,15.56,15.95,16.52,17.21,18.15,18.66,19.21,19.93,20.43,20.73,21.34,21.36,21.71,21.71,21.75,21.74,21.82,21.95,21.95,21.89
6,Яловичина,Кілограм,89.46,93.68,95.69,97.49,99.28,102.70,105.43,106.84,110.10,112.12,112.53,114.30,117.14,120.39,122.16,124.70,124.48,124.41,124.51,124.99,126.00,126.93,127.43,128.12,129.06,128.36,127.56,128.50,128.71,128.50,129.37,130.24,131.12,132.20,132.05,132.81,134.85,136.69,138.07,141.06,141.73,142.65,142.44,142.59,143.27,143.29,144.16,144.82,149.51,153.99,157.24,159.13,160.30,160.94,162.45,165.00,172.04,175.51,179.37,182.84,195.61,208.02,221.45,216.39,211.23,205.59,200.63,200.20,200.92,203.45,200.65,203.18,204.95,203.61,206.36,210.95,214.60,219.04,223.52,227.99,230.59,233.76,238.05,243.64,251.64,260.15,263.97,266.10,268.23,269.24,270.01,270.56,273.80,279.76,284.53,288.73,293.27,297.92,303.16,307.16,314.73,323.18,329.33,332.53,343.79,348.55,349.24,352.21
7,Проїзд у міському транспорті,Квиток,2.46,2.51,2.62,2.77,2.79,2.82,2.88,2.96,3.03,3.06,3.11,3.12,3.17,3.22,3.23,3.40,3.47,3.50,3.75,4.03,4.10,4.10,4.24,4.44,4.47,4.67,4.82,4.88,4.91,4.97,5.00,5.02,5.04,5.06,5.10,5.11,5.31,5.37,5.39,5.39,5.39,5.41,5.41,5.51,5.51,5.51,5.51,5.51,5.57,5.58,5.61,5.68,5.80,6.21,6.46,6.87,6.91,7.07,7.27,7.32,7.33,7.53,7.60,7.44,7.54,7.77,8.11,8.44,8.48,8.57,8.64,8.57,8.58,8.58,8.58,8.58,8.57,8.57,8.59,8.63,8.69,8.69,8.69,8.98,9.09,9.09,9.16,9.31,9.31,9.35,9.49,9.62,9.73,9.73,9.73,10.26,10.58,10.59,11.09,11.18,11.50,11.84,11.87,11.87,11.92,11.94,11.94,11.94

**Відображення всіх колонок.** `pd.set_option('display.max_columns', None)` знімає ліміт на кількість колонок при виведенні. Pandas за замовчуванням скорочує їх до кількох з «...». Хочеця побачити наші дані у всій їх красі

In [36]:
pd.set_option('display.max_columns', None)
df

,Тип товарів і послуг,Одиниця виміру,2017-M01,2017-M02,2017-M03,2017-M04,2017-M05,2017-M06,2017-M07,2017-M08,2017-M09,2017-M10,2017-M11,2017-M12,2018-M01,2018-M02,2018-M03,2018-M04,2018-M05,2018-M06,2018-M07,2018-M08,2018-M09,2018-M10,2018-M11,2018-M12,2019-M01,2019-M02,2019-M03,2019-M04,2019-M05,2019-M06,2019-M07,2019-M08,2019-M09,2019-M10,2019-M11,2019-M12,2020-M01,2020-M02,2020-M03,2020-M04,2020-M05,2020-M06,2020-M07,2020-M08,2020-M09,2020-M10,2020-M11,2020-M12,2021-M01,2021-M02,2021-M03,2021-M04,2021-M05,2021-M06,2021-M07,2021-M08,2021-M09,2021-M10,2021-M11,2021-M12,2022-M01,2022-M02,2022-M03,2022-M04,2022-M05,2022-M06,2022-M07,2022-M08,2022-M09,2022-M10,2022-M11,2022-M12,2023-M01,2023-M02,2023-M03,2023-M04,2023-M05,2023-M06,2023-M07,2023-M08,2023-M09,2023-M10,2023-M11,2023-M12,2024-M01,2024-M02,2024-M03,2024-M04,2024-M05,2024-M06,2024-M07,2024-M08,2024-M09,2024-M10,2024-M11,2024-M12,2025-M01,2025-M02,2025-M03,2025-M04,2025-M05,2025-M06,2025-M07,2025-M08,2025-M09,2025-M10,2025-M11,2025-M12
0,Птиця (тушки курячі),Кілограм,42.12,42.70,42.95,43.83,44.45,45.35,49.85,53.94,55.50,55.26,53.95,53.90,54.86,53.72,54.08,55.17,54.81,54.78,54.90,55.69,58.62,58.64,58.32,57.83,58.66,58.15,58.32,58.40,59.37,60.22,61.78,62.22,62.27,62.07,60.74,59.37,58.23,55.09,54.12,52.22,49.59,50.50,51.25,52.18,52.93,54.38,55.17,55.96,57.40,60.13,63.06,65.35,67.25,68.19,69.34,69.94,71.40,72.42,71.02,70.82,73.52,74.12,76.19,76.04,74.81,79.54,80.83,82.43,82.43,82.96,80.49,81.29,82.45,84.63,86.71,87.67,87.56,88.69,90.37,91.43,91.50,91.67,91.27,90.25,89.92,88.31,87.89,88.03,89.28,87.35,86.76,86.79,90.95,92.22,92.38,92.55,91.45,91.85,94.95,98.15,107.22,113.94,115.55,117.95,118.03,119.98,117.93,116.20
1,"Молоко пастеризоване жирністю до 2,6% включно",1000 г,17.93,18.58,19.04,19.26,19.35,19.29,19.40,19.61,19.95,20.70,21.27,21.77,22.01,21.95,22.13,22.03,22.13,22.02,21.90,21.99,22.36,22.85,23.39,23.73,23.87,24.13,24.18,24.32,24.25,24.15,24.23,24.43,24.73,25.14,25.22,25.31,24.91,24.99,25.00,25.01,25.09,24.95,24.91,24.83,25.00,25.19,25.39,25.60,25.41,25.83,25.96,25.99,26.44,26.42,26.50,26.62,27.20,27.63,27.96,28.55,28.93,29.37,30.53,31.46,31.92,32.29,32.61,32.40,32.90,33.27,33.86,34.28,35.24,35.42,35.90,35.69,35.66,35.78,36.10,36.33,36.23,36.63,37.09,37.69,38.15,38.70,38.98,39.41,38.65,38.73,39.01,39.40,40.13,41.62,43.71,45.64,45.89,46.25,47.15,47.71,47.39,47.18,47.10,47.72,47.45,49.20,49.05,49.56
2,Картопля,Кілограм,5.58,6.11,6.25,6.71,8.36,11.12,8.99,7.44,6.76,6.19,5.95,6.00,6.43,6.89,7.58,7.83,7.54,8.73,7.95,7.56,6.86,6.52,6.76,7.99,9.33,10.09,10.16,10.73,14.07,17.26,15.30,15.02,14.63,15.29,14.14,13.52,13.13,12.80,12.89,14.75,15.27,16.06,12.67,10.02,9.08,8.96,9.23,10.15,11.14,11.87,12.17,11.92,11.96,13.30,11.79,8.66,8.32,8.69,8.61,8.76,9.29,9.54,11.70,10.23,9.64,12.24,18.93,13.56,10.84,9.91,9.13,9.20,9.40,9.57,9.55,9.49,9.89,12.04,20.25,12.87,10.95,10.16,11.90,15.13,21.46,22.75,22.73,22.45,24.53,28.39,20.08,19.73,20.67,25.85,29.79,29.74,30.09,29.87,30.12,30.63,31.95,34.73,24.89,21.24,17.93,16.85,15.79,14.76
3,Хліб пшеничний з борошна першого ґатунку,Кілограм,11.99,12.41,12.67,12.78,12.87,13.00,13.11,13.28,13.50,13.72,13.98,14.19,14.41,14.68,14.90,15.14,15.27,15.35,15.49,15.68,16.14,16.54,17.22,17.48,17.78,18.01,18.22,18.41,18.68,18.99,19.08,19.15,19.24,19.31,19.55,19.58,19.74,19.78,19.81,19.86,19.98,20.09,20.12,20.16,20.37,20.62,20.99,21.40,21.98,22.52,23.19,23.50,23.76,23.80,23.86,23.91,24.48,25.18,25.78,26.29,27.11,28.29,29.50,29.77,30.64,31.65,32.10,32.00,32.20,32.76,32.63,33.23,34.20,34.64,34.67,34.81,34.72,34.65,34.88,35.11,35.16,35.47,35.77,36.02,35.72,35.94,36.38,36.64,36.76,37.09,38.35,39.59,40.03,40.81,41.29,42.52,43.42,43.69,44.25,45.06,45.38,46.19,46.31,46.39,47.07,47.68,48.26,48.81
4,Бензин А-92,Літр,23.19,23.73,23.75,24.05,24.24,24.04,23.81,23.83,24.35,25.68,26.61,27.30,28.58,29.20,28.50,28.28,28.34,28.39,28.24,28.49,30.09,31.79,31.12,29.31,27.58,27.29,27.23,27.75,28.93,28.87,27.96,27.65,27.58,27.55,27.49,26.98,25.78,25.41,25.12,22.84,20.85,20.79,21.49,22.11,22.24,22.41,23.12,23.82,24.52,26.07,27.54,27.73,28.16,28.36,29.18,29.32,29.15,29.97,30.80,29.63,30.52,33.19,35.45,34.11,40.87,50.38,49.06,48.44,47.88,47.65,48.23,49.96,49.10,46.95,45.74,44.42,43.16,41.95,45.31,49.01,51.70,53.35,52.80,49.65,47.51,47.56,48.97,51.08,51.96,52.65,53.14,53.03,53.34,53.30,52.84,52.60,53.34,53.52,53.06,52.29,51.63,53.48,56.35,56.16,55.70,55.90,55.70,55.91
5,Борошно пшеничне,Кілограм,8.53,8.68,8.94,9.08,9.15,9.16,9.17,9.12,9.19,9.21,9.32,9.44,9.55,9.65,9.74,9.79,9.88,9.99,10.04,10.23,10.74,11.10,11.24,11.34,11.36,11.50,11.64,11.71,11.82,11.83,11.84,11.74,11.65,11.47,11.28,11.22,11.10,11.18,11.34,11.60,11.75,11.79,11.67,11.57,11.43,11.61,12.31,12.70,13.18,13.75,14.14,14.49,14.38,14.33,14.25,14.30,14.38,14.48,14.66,15.01,15.48,15.65,16.81,18.04,18.34,18.29,17.89,17.41,17.23,16.94,16.73,16.79,16.85,16.71,16.68,16.62,16.55,16.40,16.29,15.89,16.03,15.89,15.81,15.85,15.69,15.79,15.68,15.52,15.56,15.95,16.52,17.21,18.15,18.66,19.21,19.93,20.43,20.73,21.34,21.36,21.71,21.71,21.75,21.74,21.82,21.95,21.95,21.89
6,Яловичина,Кілограм,89.46,93.68,95.69,97.49,99.28,102.70,105.43,106.84,110.10,112.12,112.53,114.30,117.14,120.39,122.16,124.70,124.48,124.41,124.51,124.99,126.00,126.93,127.43,128.12,129.06,128.36,127.56,128.50,128.71,128.50,129.37,130.24,131.12,132.20,132.05,132.81,134.85,136.69,138.07,141.06,141.73,142.65,142.44,142.59,143.27,143.29,144.16,144.82,149.51,153.99,157.24,159.13,160.30,160.94,162.45,165.00,172.04,175.51,179.37,182.84,195.61,208.02,221.45,216.39,211.23,205.59,200.63,200.20,200.92,203.45,200.65,203.18,204.95,203.61,206.36,210.95,214.60,219.04,223.52,227.99,230.59,233.76,238.05,243.64,251.64,260.15,263.97,266.10,268.23,269.24,270.01,270.56,273.80,279.76,284.53,288.73,293.27,297.92,303.16,307.16,314.73,323.18,329.33,332.53,343.79,348.55,349.24,352.21
7,Проїзд у міському транспорті,Квиток,2.46,2.51,2.62,2.77,2.79,2.82,2.88,2.96,3.03,3.06,3.11,3.12,3.17,3.22,3.23,3.40,3.47,3.50,3.75,4.03,4.10,4.10,4.24,4.44,4.47,4.67,4.82,4.88,4.91,4.97,5.00,5.02,5.04,5.06,5.10,5.11,5.31,5.37,5.39,5.39,5.39,5.41,5.41,5.51,5.51,5.51,5.51,5.51,5.57,5.58,5.61,5.68,5.80,6.21,6.46,6.87,6.91,7.07,7.27,7.32,7.33,7.53,7.60,7.44,7.54,7.77,8.11,8.44,8.48,8.57,8.64,8.57,8.58,8.58,8.58,8.58,8.57,8.57,8.59,8.63,8.69,8.69,8.69,8.98,9.09,9.09,9.16,9.31,9.31,9.35,9.49,9.62,9.73,9.73,9.73,10.26,10.58,10.59,11.09,11.18,11.50,11.84,11.87,11.87,11.92,11.94,11.94,11.94

**Очищення типів даних.** `pd.to_numeric(..., errors='coerce')` конвертує всі місячні колонки в тип float. Нечислові значення (порожні рядки, «Явищ не було» тощо) стають NaN. Потрібно для коректної статистики.

In [37]:
df[month_cols] = df[month_cols].apply(pd.to_numeric, errors='coerce')

**Перевірка пропусків.** `df.isna().sum().sum()` підраховує загальну кількість NaN. Якщо вони є — показуємо рядки з пропусками. Це допомагає вирішити: заповнювати, інтерполювати чи видаляти.

In [38]:
total_nans = df.isna().sum().sum()

if total_nans > 0:
    print("Рядки з пропущеними значеннями:")
    display(df[df.isna().any(axis=1)])
else:
    print("Пропущених значень не знайдено.")

Пропущених значень не знайдено.

In [39]:
df

,Тип товарів і послуг,Одиниця виміру,2017-M01,2017-M02,2017-M03,2017-M04,2017-M05,2017-M06,2017-M07,2017-M08,2017-M09,2017-M10,2017-M11,2017-M12,2018-M01,2018-M02,2018-M03,2018-M04,2018-M05,2018-M06,2018-M07,2018-M08,2018-M09,2018-M10,2018-M11,2018-M12,2019-M01,2019-M02,2019-M03,2019-M04,2019-M05,2019-M06,2019-M07,2019-M08,2019-M09,2019-M10,2019-M11,2019-M12,2020-M01,2020-M02,2020-M03,2020-M04,2020-M05,2020-M06,2020-M07,2020-M08,2020-M09,2020-M10,2020-M11,2020-M12,2021-M01,2021-M02,2021-M03,2021-M04,2021-M05,2021-M06,2021-M07,2021-M08,2021-M09,2021-M10,2021-M11,2021-M12,2022-M01,2022-M02,2022-M03,2022-M04,2022-M05,2022-M06,2022-M07,2022-M08,2022-M09,2022-M10,2022-M11,2022-M12,2023-M01,2023-M02,2023-M03,2023-M04,2023-M05,2023-M06,2023-M07,2023-M08,2023-M09,2023-M10,2023-M11,2023-M12,2024-M01,2024-M02,2024-M03,2024-M04,2024-M05,2024-M06,2024-M07,2024-M08,2024-M09,2024-M10,2024-M11,2024-M12,2025-M01,2025-M02,2025-M03,2025-M04,2025-M05,2025-M06,2025-M07,2025-M08,2025-M09,2025-M10,2025-M11,2025-M12
0,Птиця (тушки курячі),Кілограм,42.12,42.70,42.95,43.83,44.45,45.35,49.85,53.94,55.50,55.26,53.95,53.90,54.86,53.72,54.08,55.17,54.81,54.78,54.90,55.69,58.62,58.64,58.32,57.83,58.66,58.15,58.32,58.40,59.37,60.22,61.78,62.22,62.27,62.07,60.74,59.37,58.23,55.09,54.12,52.22,49.59,50.50,51.25,52.18,52.93,54.38,55.17,55.96,57.40,60.13,63.06,65.35,67.25,68.19,69.34,69.94,71.40,72.42,71.02,70.82,73.52,74.12,76.19,76.04,74.81,79.54,80.83,82.43,82.43,82.96,80.49,81.29,82.45,84.63,86.71,87.67,87.56,88.69,90.37,91.43,91.50,91.67,91.27,90.25,89.92,88.31,87.89,88.03,89.28,87.35,86.76,86.79,90.95,92.22,92.38,92.55,91.45,91.85,94.95,98.15,107.22,113.94,115.55,117.95,118.03,119.98,117.93,116.20
1,"Молоко пастеризоване жирністю до 2,6% включно",1000 г,17.93,18.58,19.04,19.26,19.35,19.29,19.40,19.61,19.95,20.70,21.27,21.77,22.01,21.95,22.13,22.03,22.13,22.02,21.90,21.99,22.36,22.85,23.39,23.73,23.87,24.13,24.18,24.32,24.25,24.15,24.23,24.43,24.73,25.14,25.22,25.31,24.91,24.99,25.00,25.01,25.09,24.95,24.91,24.83,25.00,25.19,25.39,25.60,25.41,25.83,25.96,25.99,26.44,26.42,26.50,26.62,27.20,27.63,27.96,28.55,28.93,29.37,30.53,31.46,31.92,32.29,32.61,32.40,32.90,33.27,33.86,34.28,35.24,35.42,35.90,35.69,35.66,35.78,36.10,36.33,36.23,36.63,37.09,37.69,38.15,38.70,38.98,39.41,38.65,38.73,39.01,39.40,40.13,41.62,43.71,45.64,45.89,46.25,47.15,47.71,47.39,47.18,47.10,47.72,47.45,49.20,49.05,49.56
2,Картопля,Кілограм,5.58,6.11,6.25,6.71,8.36,11.12,8.99,7.44,6.76,6.19,5.95,6.00,6.43,6.89,7.58,7.83,7.54,8.73,7.95,7.56,6.86,6.52,6.76,7.99,9.33,10.09,10.16,10.73,14.07,17.26,15.30,15.02,14.63,15.29,14.14,13.52,13.13,12.80,12.89,14.75,15.27,16.06,12.67,10.02,9.08,8.96,9.23,10.15,11.14,11.87,12.17,11.92,11.96,13.30,11.79,8.66,8.32,8.69,8.61,8.76,9.29,9.54,11.70,10.23,9.64,12.24,18.93,13.56,10.84,9.91,9.13,9.20,9.40,9.57,9.55,9.49,9.89,12.04,20.25,12.87,10.95,10.16,11.90,15.13,21.46,22.75,22.73,22.45,24.53,28.39,20.08,19.73,20.67,25.85,29.79,29.74,30.09,29.87,30.12,30.63,31.95,34.73,24.89,21.24,17.93,16.85,15.79,14.76
3,Хліб пшеничний з борошна першого ґатунку,Кілограм,11.99,12.41,12.67,12.78,12.87,13.00,13.11,13.28,13.50,13.72,13.98,14.19,14.41,14.68,14.90,15.14,15.27,15.35,15.49,15.68,16.14,16.54,17.22,17.48,17.78,18.01,18.22,18.41,18.68,18.99,19.08,19.15,19.24,19.31,19.55,19.58,19.74,19.78,19.81,19.86,19.98,20.09,20.12,20.16,20.37,20.62,20.99,21.40,21.98,22.52,23.19,23.50,23.76,23.80,23.86,23.91,24.48,25.18,25.78,26.29,27.11,28.29,29.50,29.77,30.64,31.65,32.10,32.00,32.20,32.76,32.63,33.23,34.20,34.64,34.67,34.81,34.72,34.65,34.88,35.11,35.16,35.47,35.77,36.02,35.72,35.94,36.38,36.64,36.76,37.09,38.35,39.59,40.03,40.81,41.29,42.52,43.42,43.69,44.25,45.06,45.38,46.19,46.31,46.39,47.07,47.68,48.26,48.81
4,Бензин А-92,Літр,23.19,23.73,23.75,24.05,24.24,24.04,23.81,23.83,24.35,25.68,26.61,27.30,28.58,29.20,28.50,28.28,28.34,28.39,28.24,28.49,30.09,31.79,31.12,29.31,27.58,27.29,27.23,27.75,28.93,28.87,27.96,27.65,27.58,27.55,27.49,26.98,25.78,25.41,25.12,22.84,20.85,20.79,21.49,22.11,22.24,22.41,23.12,23.82,24.52,26.07,27.54,27.73,28.16,28.36,29.18,29.32,29.15,29.97,30.80,29.63,30.52,33.19,35.45,34.11,40.87,50.38,49.06,48.44,47.88,47.65,48.23,49.96,49.10,46.95,45.74,44.42,43.16,41.95,45.31,49.01,51.70,53.35,52.80,49.65,47.51,47.56,48.97,51.08,51.96,52.65,53.14,53.03,53.34,53.30,52.84,52.60,53.34,53.52,53.06,52.29,51.63,53.48,56.35,56.16,55.70,55.90,55.70,55.91
5,Борошно пшеничне,Кілограм,8.53,8.68,8.94,9.08,9.15,9.16,9.17,9.12,9.19,9.21,9.32,9.44,9.55,9.65,9.74,9.79,9.88,9.99,10.04,10.23,10.74,11.10,11.24,11.34,11.36,11.50,11.64,11.71,11.82,11.83,11.84,11.74,11.65,11.47,11.28,11.22,11.10,11.18,11.34,11.60,11.75,11.79,11.67,11.57,11.43,11.61,12.31,12.70,13.18,13.75,14.14,14.49,14.38,14.33,14.25,14.30,14.38,14.48,14.66,15.01,15.48,15.65,16.81,18.04,18.34,18.29,17.89,17.41,17.23,16.94,16.73,16.79,16.85,16.71,16.68,16.62,16.55,16.40,16.29,15.89,16.03,15.89,15.81,15.85,15.69,15.79,15.68,15.52,15.56,15.95,16.52,17.21,18.15,18.66,19.21,19.93,20.43,20.73,21.34,21.36,21.71,21.71,21.75,21.74,21.82,21.95,21.95,21.89
6,Яловичина,Кілограм,89.46,93.68,95.69,97.49,99.28,102.70,105.43,106.84,110.10,112.12,112.53,114.30,117.14,120.39,122.16,124.70,124.48,124.41,124.51,124.99,126.00,126.93,127.43,128.12,129.06,128.36,127.56,128.50,128.71,128.50,129.37,130.24,131.12,132.20,132.05,132.81,134.85,136.69,138.07,141.06,141.73,142.65,142.44,142.59,143.27,143.29,144.16,144.82,149.51,153.99,157.24,159.13,160.30,160.94,162.45,165.00,172.04,175.51,179.37,182.84,195.61,208.02,221.45,216.39,211.23,205.59,200.63,200.20,200.92,203.45,200.65,203.18,204.95,203.61,206.36,210.95,214.60,219.04,223.52,227.99,230.59,233.76,238.05,243.64,251.64,260.15,263.97,266.10,268.23,269.24,270.01,270.56,273.80,279.76,284.53,288.73,293.27,297.92,303.16,307.16,314.73,323.18,329.33,332.53,343.79,348.55,349.24,352.21
7,Проїзд у міському транспорті,Квиток,2.46,2.51,2.62,2.77,2.79,2.82,2.88,2.96,3.03,3.06,3.11,3.12,3.17,3.22,3.23,3.40,3.47,3.50,3.75,4.03,4.10,4.10,4.24,4.44,4.47,4.67,4.82,4.88,4.91,4.97,5.00,5.02,5.04,5.06,5.10,5.11,5.31,5.37,5.39,5.39,5.39,5.41,5.41,5.51,5.51,5.51,5.51,5.51,5.57,5.58,5.61,5.68,5.80,6.21,6.46,6.87,6.91,7.07,7.27,7.32,7.33,7.53,7.60,7.44,7.54,7.77,8.11,8.44,8.48,8.57,8.64,8.57,8.58,8.58,8.58,8.58,8.57,8.57,8.59,8.63,8.69,8.69,8.69,8.98,9.09,9.09,9.16,9.31,9.31,9.35,9.49,9.62,9.73,9.73,9.73,10.26,10.58,10.59,11.09,11.18,11.50,11.84,11.87,11.87,11.92,11.94,11.94,11.94

**Уніфікація одиниць виміру.** Для молока одиниця — «1000 г». Замінюємо на «Кілограм» для єдиності та читабельності.

In [40]:
df = df.replace('1000 г', 'Кілограм')

df

,Тип товарів і послуг,Одиниця виміру,2017-M01,2017-M02,2017-M03,2017-M04,2017-M05,2017-M06,2017-M07,2017-M08,2017-M09,2017-M10,2017-M11,2017-M12,2018-M01,2018-M02,2018-M03,2018-M04,2018-M05,2018-M06,2018-M07,2018-M08,2018-M09,2018-M10,2018-M11,2018-M12,2019-M01,2019-M02,2019-M03,2019-M04,2019-M05,2019-M06,2019-M07,2019-M08,2019-M09,2019-M10,2019-M11,2019-M12,2020-M01,2020-M02,2020-M03,2020-M04,2020-M05,2020-M06,2020-M07,2020-M08,2020-M09,2020-M10,2020-M11,2020-M12,2021-M01,2021-M02,2021-M03,2021-M04,2021-M05,2021-M06,2021-M07,2021-M08,2021-M09,2021-M10,2021-M11,2021-M12,2022-M01,2022-M02,2022-M03,2022-M04,2022-M05,2022-M06,2022-M07,2022-M08,2022-M09,2022-M10,2022-M11,2022-M12,2023-M01,2023-M02,2023-M03,2023-M04,2023-M05,2023-M06,2023-M07,2023-M08,2023-M09,2023-M10,2023-M11,2023-M12,2024-M01,2024-M02,2024-M03,2024-M04,2024-M05,2024-M06,2024-M07,2024-M08,2024-M09,2024-M10,2024-M11,2024-M12,2025-M01,2025-M02,2025-M03,2025-M04,2025-M05,2025-M06,2025-M07,2025-M08,2025-M09,2025-M10,2025-M11,2025-M12
0,Птиця (тушки курячі),Кілограм,42.12,42.70,42.95,43.83,44.45,45.35,49.85,53.94,55.50,55.26,53.95,53.90,54.86,53.72,54.08,55.17,54.81,54.78,54.90,55.69,58.62,58.64,58.32,57.83,58.66,58.15,58.32,58.40,59.37,60.22,61.78,62.22,62.27,62.07,60.74,59.37,58.23,55.09,54.12,52.22,49.59,50.50,51.25,52.18,52.93,54.38,55.17,55.96,57.40,60.13,63.06,65.35,67.25,68.19,69.34,69.94,71.40,72.42,71.02,70.82,73.52,74.12,76.19,76.04,74.81,79.54,80.83,82.43,82.43,82.96,80.49,81.29,82.45,84.63,86.71,87.67,87.56,88.69,90.37,91.43,91.50,91.67,91.27,90.25,89.92,88.31,87.89,88.03,89.28,87.35,86.76,86.79,90.95,92.22,92.38,92.55,91.45,91.85,94.95,98.15,107.22,113.94,115.55,117.95,118.03,119.98,117.93,116.20
1,"Молоко пастеризоване жирністю до 2,6% включно",Кілограм,17.93,18.58,19.04,19.26,19.35,19.29,19.40,19.61,19.95,20.70,21.27,21.77,22.01,21.95,22.13,22.03,22.13,22.02,21.90,21.99,22.36,22.85,23.39,23.73,23.87,24.13,24.18,24.32,24.25,24.15,24.23,24.43,24.73,25.14,25.22,25.31,24.91,24.99,25.00,25.01,25.09,24.95,24.91,24.83,25.00,25.19,25.39,25.60,25.41,25.83,25.96,25.99,26.44,26.42,26.50,26.62,27.20,27.63,27.96,28.55,28.93,29.37,30.53,31.46,31.92,32.29,32.61,32.40,32.90,33.27,33.86,34.28,35.24,35.42,35.90,35.69,35.66,35.78,36.10,36.33,36.23,36.63,37.09,37.69,38.15,38.70,38.98,39.41,38.65,38.73,39.01,39.40,40.13,41.62,43.71,45.64,45.89,46.25,47.15,47.71,47.39,47.18,47.10,47.72,47.45,49.20,49.05,49.56
2,Картопля,Кілограм,5.58,6.11,6.25,6.71,8.36,11.12,8.99,7.44,6.76,6.19,5.95,6.00,6.43,6.89,7.58,7.83,7.54,8.73,7.95,7.56,6.86,6.52,6.76,7.99,9.33,10.09,10.16,10.73,14.07,17.26,15.30,15.02,14.63,15.29,14.14,13.52,13.13,12.80,12.89,14.75,15.27,16.06,12.67,10.02,9.08,8.96,9.23,10.15,11.14,11.87,12.17,11.92,11.96,13.30,11.79,8.66,8.32,8.69,8.61,8.76,9.29,9.54,11.70,10.23,9.64,12.24,18.93,13.56,10.84,9.91,9.13,9.20,9.40,9.57,9.55,9.49,9.89,12.04,20.25,12.87,10.95,10.16,11.90,15.13,21.46,22.75,22.73,22.45,24.53,28.39,20.08,19.73,20.67,25.85,29.79,29.74,30.09,29.87,30.12,30.63,31.95,34.73,24.89,21.24,17.93,16.85,15.79,14.76
3,Хліб пшеничний з борошна першого ґатунку,Кілограм,11.99,12.41,12.67,12.78,12.87,13.00,13.11,13.28,13.50,13.72,13.98,14.19,14.41,14.68,14.90,15.14,15.27,15.35,15.49,15.68,16.14,16.54,17.22,17.48,17.78,18.01,18.22,18.41,18.68,18.99,19.08,19.15,19.24,19.31,19.55,19.58,19.74,19.78,19.81,19.86,19.98,20.09,20.12,20.16,20.37,20.62,20.99,21.40,21.98,22.52,23.19,23.50,23.76,23.80,23.86,23.91,24.48,25.18,25.78,26.29,27.11,28.29,29.50,29.77,30.64,31.65,32.10,32.00,32.20,32.76,32.63,33.23,34.20,34.64,34.67,34.81,34.72,34.65,34.88,35.11,35.16,35.47,35.77,36.02,35.72,35.94,36.38,36.64,36.76,37.09,38.35,39.59,40.03,40.81,41.29,42.52,43.42,43.69,44.25,45.06,45.38,46.19,46.31,46.39,47.07,47.68,48.26,48.81
4,Бензин А-92,Літр,23.19,23.73,23.75,24.05,24.24,24.04,23.81,23.83,24.35,25.68,26.61,27.30,28.58,29.20,28.50,28.28,28.34,28.39,28.24,28.49,30.09,31.79,31.12,29.31,27.58,27.29,27.23,27.75,28.93,28.87,27.96,27.65,27.58,27.55,27.49,26.98,25.78,25.41,25.12,22.84,20.85,20.79,21.49,22.11,22.24,22.41,23.12,23.82,24.52,26.07,27.54,27.73,28.16,28.36,29.18,29.32,29.15,29.97,30.80,29.63,30.52,33.19,35.45,34.11,40.87,50.38,49.06,48.44,47.88,47.65,48.23,49.96,49.10,46.95,45.74,44.42,43.16,41.95,45.31,49.01,51.70,53.35,52.80,49.65,47.51,47.56,48.97,51.08,51.96,52.65,53.14,53.03,53.34,53.30,52.84,52.60,53.34,53.52,53.06,52.29,51.63,53.48,56.35,56.16,55.70,55.90,55.70,55.91
5,Борошно пшеничне,Кілограм,8.53,8.68,8.94,9.08,9.15,9.16,9.17,9.12,9.19,9.21,9.32,9.44,9.55,9.65,9.74,9.79,9.88,9.99,10.04,10.23,10.74,11.10,11.24,11.34,11.36,11.50,11.64,11.71,11.82,11.83,11.84,11.74,11.65,11.47,11.28,11.22,11.10,11.18,11.34,11.60,11.75,11.79,11.67,11.57,11.43,11.61,12.31,12.70,13.18,13.75,14.14,14.49,14.38,14.33,14.25,14.30,14.38,14.48,14.66,15.01,15.48,15.65,16.81,18.04,18.34,18.29,17.89,17.41,17.23,16.94,16.73,16.79,16.85,16.71,16.68,16.62,16.55,16.40,16.29,15.89,16.03,15.89,15.81,15.85,15.69,15.79,15.68,15.52,15.56,15.95,16.52,17.21,18.15,18.66,19.21,19.93,20.43,20.73,21.34,21.36,21.71,21.71,21.75,21.74,21.82,21.95,21.95,21.89
6,Яловичина,Кілограм,89.46,93.68,95.69,97.49,99.28,102.70,105.43,106.84,110.10,112.12,112.53,114.30,117.14,120.39,122.16,124.70,124.48,124.41,124.51,124.99,126.00,126.93,127.43,128.12,129.06,128.36,127.56,128.50,128.71,128.50,129.37,130.24,131.12,132.20,132.05,132.81,134.85,136.69,138.07,141.06,141.73,142.65,142.44,142.59,143.27,143.29,144.16,144.82,149.51,153.99,157.24,159.13,160.30,160.94,162.45,165.00,172.04,175.51,179.37,182.84,195.61,208.02,221.45,216.39,211.23,205.59,200.63,200.20,200.92,203.45,200.65,203.18,204.95,203.61,206.36,210.95,214.60,219.04,223.52,227.99,230.59,233.76,238.05,243.64,251.64,260.15,263.97,266.10,268.23,269.24,270.01,270.56,273.80,279.76,284.53,288.73,293.27,297.92,303.16,307.16,314.73,323.18,329.33,332.53,343.79,348.55,349.24,352.21
7,Проїзд у міському транспорті,Квиток,2.46,2.51,2.62,2.77,2.79,2.82,2.88,2.96,3.03,3.06,3.11,3.12,3.17,3.22,3.23,3.40,3.47,3.50,3.75,4.03,4.10,4.10,4.24,4.44,4.47,4.67,4.82,4.88,4.91,4.97,5.00,5.02,5.04,5.06,5.10,5.11,5.31,5.37,5.39,5.39,5.39,5.41,5.41,5.51,5.51,5.51,5.51,5.51,5.57,5.58,5.61,5.68,5.80,6.21,6.46,6.87,6.91,7.07,7.27,7.32,7.33,7.53,7.60,7.44,7.54,7.77,8.11,8.44,8.48,8.57,8.64,8.57,8.58,8.58,8.58,8.58,8.57,8.57,8.59,8.63,8.69,8.69,8.69,8.98,9.09,9.09,9.16,9.31,9.31,9.35,9.49,9.62,9.73,9.73,9.73,10.26,10.58,10.59,11.09,11.18,11.50,11.84,11.87,11.87,11.92,11.94,11.94,11.94

**Long-формат (melt).** Перетворюємо wide-формат (кожен місяць — окрема колонка) в long-формат (кожен місяць — окремий рядок). `id_vars` — метадані, `value_vars` — місячні колонки, `value_name` — стовпець з цінами. `.dropna()` видаляє рядки з пропусками. Такий формат зручний для groupby, describe та гістограм.

In [41]:
df_long = df.melt(
    id_vars=['Тип товарів і послуг', 'Одиниця виміру'],
    value_vars=month_cols,
    var_name='Період',
    value_name='Ціна'
).dropna()

df_long

,Тип товарів і послуг,Одиниця виміру,Період,Ціна
0,Птиця (тушки курячі),Кілограм,2017-M01,42.12
1,"Молоко пастеризоване жирністю до 2,6% включно",Кілограм,2017-M01,17.93
2,Картопля,Кілограм,2017-M01,5.58
3,Хліб пшеничний з борошна першого ґатунку,Кілограм,2017-M01,11.99
4,Бензин А-92,Літр,2017-M01,23.19
...,...,...,...,...
859,Хліб пшеничний з борошна першого ґатунку,Кілограм,2025-M12,48.81
860,Бензин А-92,Літр,2025-M12,55.91
861,Борошно пшеничне,Кілограм,2025-M12,21.89
862,Яловичина,Кілограм,2025-M12,352.21
863,Проїзд у міському транспорті,Квиток,2025-M12,11.94